/*
 *  Brandon Hopkins - C3290146
 *  Software Engineering - COMP2230
 *  Assignment 1
 */

public class TableBuilder
{
	/** Builds a lookup table for a line of passed size. */
    public static int[] buildTable(int table)
    {
        String hash_4 =
		(
			"E,E,E,E\n" +
			"E,E,E,X\n" +
			"E,E,E,O\n" +
			"E,E,X,E\n" +
			"E,E,X,X\n" +
			"E,E,X,O\n" +
			"E,E,O,E\n" +
			"E,E,O,X\n" +
			"E,E,O,O\n" +
			"E,X,E,E\n" +
			"E,X,E,X\n" +
			"E,X,E,O\n" +
			"E,X,X,E\n" +
			"E,X,X,X\n" +
			"E,X,X,O\n" +
			"E,X,O,E\n" +
			"E,X,O,X\n" +
			"E,X,O,O\n" +
			"E,O,E,E\n" +
			"E,O,E,X\n" +
			"E,O,E,O\n" +
			"E,O,X,E\n" +
			"E,O,X,X\n" +
			"E,O,X,O\n" +
			"E,O,O,E\n" +
			"E,O,O,X\n" +
			"E,O,O,O\n" +
			"X,E,E,E\n" +
			"X,E,E,X\n" +
			"X,E,E,O\n" +
			"X,E,X,E\n" +
			"X,E,X,X\n" +
			"X,E,X,O\n" +
			"X,E,O,E\n" +
			"X,E,O,X\n" +
			"X,E,O,O\n" +
			"X,X,E,E\n" +
			"X,X,E,X\n" +
			"X,X,E,O\n" +
			"X,X,X,E\n" +
			"X,X,X,X\n" +
			"X,X,X,O\n" +
			"X,X,O,E\n" +
			"X,X,O,X\n" +
			"X,X,O,O\n" +
			"X,O,E,E\n" +
			"X,O,E,X\n" +
			"X,O,E,O\n" +
			"X,O,X,E\n" +
			"X,O,X,X\n" +
			"X,O,X,O\n" +
			"X,O,O,E\n" +
			"X,O,O,X\n" +
			"X,O,O,O\n" +
			"O,E,E,E\n" +
			"O,E,E,X\n" +
			"O,E,E,O\n" +
			"O,E,X,E\n" +
			"O,E,X,X\n" +
			"O,E,X,O\n" +
			"O,E,O,E\n" +
			"O,E,O,X\n" +
			"O,E,O,O\n" +
			"O,X,E,E\n" +
			"O,X,E,X\n" +
			"O,X,E,O\n" +
			"O,X,X,E\n" +
			"O,X,X,X\n" +
			"O,X,X,O\n" +
			"O,X,O,E\n" +
			"O,X,O,X\n" +
			"O,X,O,O\n" +
			"O,O,E,E\n" +
			"O,O,E,X\n" +
			"O,O,E,O\n" +
			"O,O,X,E\n" +
			"O,O,X,X\n" +
			"O,O,X,O\n" +
			"O,O,O,E\n" +
			"O,O,O,X\n" +
			"O,O,O,O\n"
		);

        String hash_5 =
		(
			"E,E,E,E,E\n" +
			"E,E,E,E,X\n" +
			"E,E,E,E,O\n" +
			"E,E,E,X,E\n" +
			"E,E,E,X,X\n" +
			"E,E,E,X,O\n" +
			"E,E,E,O,E\n" +
			"E,E,E,O,X\n" +
			"E,E,E,O,O\n" +
			"E,E,X,E,E\n" +
			"E,E,X,E,X\n" +
			"E,E,X,E,O\n" +
			"E,E,X,X,E\n" +
			"E,E,X,X,X\n" +
			"E,E,X,X,O\n" +
			"E,E,X,O,E\n" +
			"E,E,X,O,X\n" +
			"E,E,X,O,O\n" +
			"E,E,O,E,E\n" +
			"E,E,O,E,X\n" +
			"E,E,O,E,O\n" +
			"E,E,O,X,E\n" +
			"E,E,O,X,X\n" +
			"E,E,O,X,O\n" +
			"E,E,O,O,E\n" +
			"E,E,O,O,X\n" +
			"E,E,O,O,O\n" +
			"E,X,E,E,E\n" +
			"E,X,E,E,X\n" +
			"E,X,E,E,O\n" +
			"E,X,E,X,E\n" +
			"E,X,E,X,X\n" +
			"E,X,E,X,O\n" +
			"E,X,E,O,E\n" +
			"E,X,E,O,X\n" +
			"E,X,E,O,O\n" +
			"E,X,X,E,E\n" +
			"E,X,X,E,X\n" +
			"E,X,X,E,O\n" +
			"E,X,X,X,E\n" +
			"E,X,X,X,X\n" +
			"E,X,X,X,O\n" +
			"E,X,X,O,E\n" +
			"E,X,X,O,X\n" +
			"E,X,X,O,O\n" +
			"E,X,O,E,E\n" +
			"E,X,O,E,X\n" +
			"E,X,O,E,O\n" +
			"E,X,O,X,E\n" +
			"E,X,O,X,X\n" +
			"E,X,O,X,O\n" +
			"E,X,O,O,E\n" +
			"E,X,O,O,X\n" +
			"E,X,O,O,O\n" +
			"E,O,E,E,E\n" +
			"E,O,E,E,X\n" +
			"E,O,E,E,O\n" +
			"E,O,E,X,E\n" +
			"E,O,E,X,X\n" +
			"E,O,E,X,O\n" +
			"E,O,E,O,E\n" +
			"E,O,E,O,X\n" +
			"E,O,E,O,O\n" +
			"E,O,X,E,E\n" +
			"E,O,X,E,X\n" +
			"E,O,X,E,O\n" +
			"E,O,X,X,E\n" +
			"E,O,X,X,X\n" +
			"E,O,X,X,O\n" +
			"E,O,X,O,E\n" +
			"E,O,X,O,X\n" +
			"E,O,X,O,O\n" +
			"E,O,O,E,E\n" +
			"E,O,O,E,X\n" +
			"E,O,O,E,O\n" +
			"E,O,O,X,E\n" +
			"E,O,O,X,X\n" +
			"E,O,O,X,O\n" +
			"E,O,O,O,E\n" +
			"E,O,O,O,X\n" +
			"E,O,O,O,O\n" +
			"X,E,E,E,E\n" +
			"X,E,E,E,X\n" +
			"X,E,E,E,O\n" +
			"X,E,E,X,E\n" +
			"X,E,E,X,X\n" +
			"X,E,E,X,O\n" +
			"X,E,E,O,E\n" +
			"X,E,E,O,X\n" +
			"X,E,E,O,O\n" +
			"X,E,X,E,E\n" +
			"X,E,X,E,X\n" +
			"X,E,X,E,O\n" +
			"X,E,X,X,E\n" +
			"X,E,X,X,X\n" +
			"X,E,X,X,O\n" +
			"X,E,X,O,E\n" +
			"X,E,X,O,X\n" +
			"X,E,X,O,O\n" +
			"X,E,O,E,E\n" +
			"X,E,O,E,X\n" +
			"X,E,O,E,O\n" +
			"X,E,O,X,E\n" +
			"X,E,O,X,X\n" +
			"X,E,O,X,O\n" +
			"X,E,O,O,E\n" +
			"X,E,O,O,X\n" +
			"X,E,O,O,O\n" +
			"X,X,E,E,E\n" +
			"X,X,E,E,X\n" +
			"X,X,E,E,O\n" +
			"X,X,E,X,E\n" +
			"X,X,E,X,X\n" +
			"X,X,E,X,O\n" +
			"X,X,E,O,E\n" +
			"X,X,E,O,X\n" +
			"X,X,E,O,O\n" +
			"X,X,X,E,E\n" +
			"X,X,X,E,X\n" +
			"X,X,X,E,O\n" +
			"X,X,X,X,E\n" +
			"X,X,X,X,X\n" +
			"X,X,X,X,O\n" +
			"X,X,X,O,E\n" +
			"X,X,X,O,X\n" +
			"X,X,X,O,O\n" +
			"X,X,O,E,E\n" +
			"X,X,O,E,X\n" +
			"X,X,O,E,O\n" +
			"X,X,O,X,E\n" +
			"X,X,O,X,X\n" +
			"X,X,O,X,O\n" +
			"X,X,O,O,E\n" +
			"X,X,O,O,X\n" +
			"X,X,O,O,O\n" +
			"X,O,E,E,E\n" +
			"X,O,E,E,X\n" +
			"X,O,E,E,O\n" +
			"X,O,E,X,E\n" +
			"X,O,E,X,X\n" +
			"X,O,E,X,O\n" +
			"X,O,E,O,E\n" +
			"X,O,E,O,X\n" +
			"X,O,E,O,O\n" +
			"X,O,X,E,E\n" +
			"X,O,X,E,X\n" +
			"X,O,X,E,O\n" +
			"X,O,X,X,E\n" +
			"X,O,X,X,X\n" +
			"X,O,X,X,O\n" +
			"X,O,X,O,E\n" +
			"X,O,X,O,X\n" +
			"X,O,X,O,O\n" +
			"X,O,O,E,E\n" +
			"X,O,O,E,X\n" +
			"X,O,O,E,O\n" +
			"X,O,O,X,E\n" +
			"X,O,O,X,X\n" +
			"X,O,O,X,O\n" +
			"X,O,O,O,E\n" +
			"X,O,O,O,X\n" +
			"X,O,O,O,O\n" +
			"O,E,E,E,E\n" +
			"O,E,E,E,X\n" +
			"O,E,E,E,O\n" +
			"O,E,E,X,E\n" +
			"O,E,E,X,X\n" +
			"O,E,E,X,O\n" +
			"O,E,E,O,E\n" +
			"O,E,E,O,X\n" +
			"O,E,E,O,O\n" +
			"O,E,X,E,E\n" +
			"O,E,X,E,X\n" +
			"O,E,X,E,O\n" +
			"O,E,X,X,E\n" +
			"O,E,X,X,X\n" +
			"O,E,X,X,O\n" +
			"O,E,X,O,E\n" +
			"O,E,X,O,X\n" +
			"O,E,X,O,O\n" +
			"O,E,O,E,E\n" +
			"O,E,O,E,X\n" +
			"O,E,O,E,O\n" +
			"O,E,O,X,E\n" +
			"O,E,O,X,X\n" +
			"O,E,O,X,O\n" +
			"O,E,O,O,E\n" +
			"O,E,O,O,X\n" +
			"O,E,O,O,O\n" +
			"O,X,E,E,E\n" +
			"O,X,E,E,X\n" +
			"O,X,E,E,O\n" +
			"O,X,E,X,E\n" +
			"O,X,E,X,X\n" +
			"O,X,E,X,O\n" +
			"O,X,E,O,E\n" +
			"O,X,E,O,X\n" +
			"O,X,E,O,O\n" +
			"O,X,X,E,E\n" +
			"O,X,X,E,X\n" +
			"O,X,X,E,O\n" +
			"O,X,X,X,E\n" +
			"O,X,X,X,X\n" +
			"O,X,X,X,O\n" +
			"O,X,X,O,E\n" +
			"O,X,X,O,X\n" +
			"O,X,X,O,O\n" +
			"O,X,O,E,E\n" +
			"O,X,O,E,X\n" +
			"O,X,O,E,O\n" +
			"O,X,O,X,E\n" +
			"O,X,O,X,X\n" +
			"O,X,O,X,O\n" +
			"O,X,O,O,E\n" +
			"O,X,O,O,X\n" +
			"O,X,O,O,O\n" +
			"O,O,E,E,E\n" +
			"O,O,E,E,X\n" +
			"O,O,E,E,O\n" +
			"O,O,E,X,E\n" +
			"O,O,E,X,X\n" +
			"O,O,E,X,O\n" +
			"O,O,E,O,E\n" +
			"O,O,E,O,X\n" +
			"O,O,E,O,O\n" +
			"O,O,X,E,E\n" +
			"O,O,X,E,X\n" +
			"O,O,X,E,O\n" +
			"O,O,X,X,E\n" +
			"O,O,X,X,X\n" +
			"O,O,X,X,O\n" +
			"O,O,X,O,E\n" +
			"O,O,X,O,X\n" +
			"O,O,X,O,O\n" +
			"O,O,O,E,E\n" +
			"O,O,O,E,X\n" +
			"O,O,O,E,O\n" +
			"O,O,O,X,E\n" +
			"O,O,O,X,X\n" +
			"O,O,O,X,O\n" +
			"O,O,O,O,E\n" +
			"O,O,O,O,X\n" +
			"O,O,O,O,O\n"
		);

        String hash_6 =
		(
			"E,E,E,E,E,E\n" +
			"E,E,E,E,E,X\n" +
			"E,E,E,E,E,O\n" +
			"E,E,E,E,X,E\n" +
			"E,E,E,E,X,X\n" +
			"E,E,E,E,X,O\n" +
			"E,E,E,E,O,E\n" +
			"E,E,E,E,O,X\n" +
			"E,E,E,E,O,O\n" +
			"E,E,E,X,E,E\n" +
			"E,E,E,X,E,X\n" +
			"E,E,E,X,E,O\n" +
			"E,E,E,X,X,E\n" +
			"E,E,E,X,X,X\n" +
			"E,E,E,X,X,O\n" +
			"E,E,E,X,O,E\n" +
			"E,E,E,X,O,X\n" +
			"E,E,E,X,O,O\n" +
			"E,E,E,O,E,E\n" +
			"E,E,E,O,E,X\n" +
			"E,E,E,O,E,O\n" +
			"E,E,E,O,X,E\n" +
			"E,E,E,O,X,X\n" +
			"E,E,E,O,X,O\n" +
			"E,E,E,O,O,E\n" +
			"E,E,E,O,O,X\n" +
			"E,E,E,O,O,O\n" +
			"E,E,X,E,E,E\n" +
			"E,E,X,E,E,X\n" +
			"E,E,X,E,E,O\n" +
			"E,E,X,E,X,E\n" +
			"E,E,X,E,X,X\n" +
			"E,E,X,E,X,O\n" +
			"E,E,X,E,O,E\n" +
			"E,E,X,E,O,X\n" +
			"E,E,X,E,O,O\n" +
			"E,E,X,X,E,E\n" +
			"E,E,X,X,E,X\n" +
			"E,E,X,X,E,O\n" +
			"E,E,X,X,X,E\n" +
			"E,E,X,X,X,X\n" +
			"E,E,X,X,X,O\n" +
			"E,E,X,X,O,E\n" +
			"E,E,X,X,O,X\n" +
			"E,E,X,X,O,O\n" +
			"E,E,X,O,E,E\n" +
			"E,E,X,O,E,X\n" +
			"E,E,X,O,E,O\n" +
			"E,E,X,O,X,E\n" +
			"E,E,X,O,X,X\n" +
			"E,E,X,O,X,O\n" +
			"E,E,X,O,O,E\n" +
			"E,E,X,O,O,X\n" +
			"E,E,X,O,O,O\n" +
			"E,E,O,E,E,E\n" +
			"E,E,O,E,E,X\n" +
			"E,E,O,E,E,O\n" +
			"E,E,O,E,X,E\n" +
			"E,E,O,E,X,X\n" +
			"E,E,O,E,X,O\n" +
			"E,E,O,E,O,E\n" +
			"E,E,O,E,O,X\n" +
			"E,E,O,E,O,O\n" +
			"E,E,O,X,E,E\n" +
			"E,E,O,X,E,X\n" +
			"E,E,O,X,E,O\n" +
			"E,E,O,X,X,E\n" +
			"E,E,O,X,X,X\n" +
			"E,E,O,X,X,O\n" +
			"E,E,O,X,O,E\n" +
			"E,E,O,X,O,X\n" +
			"E,E,O,X,O,O\n" +
			"E,E,O,O,E,E\n" +
			"E,E,O,O,E,X\n" +
			"E,E,O,O,E,O\n" +
			"E,E,O,O,X,E\n" +
			"E,E,O,O,X,X\n" +
			"E,E,O,O,X,O\n" +
			"E,E,O,O,O,E\n" +
			"E,E,O,O,O,X\n" +
			"E,E,O,O,O,O\n" +
			"E,X,E,E,E,E\n" +
			"E,X,E,E,E,X\n" +
			"E,X,E,E,E,O\n" +
			"E,X,E,E,X,E\n" +
			"E,X,E,E,X,X\n" +
			"E,X,E,E,X,O\n" +
			"E,X,E,E,O,E\n" +
			"E,X,E,E,O,X\n" +
			"E,X,E,E,O,O\n" +
			"E,X,E,X,E,E\n" +
			"E,X,E,X,E,X\n" +
			"E,X,E,X,E,O\n" +
			"E,X,E,X,X,E\n" +
			"E,X,E,X,X,X\n" +
			"E,X,E,X,X,O\n" +
			"E,X,E,X,O,E\n" +
			"E,X,E,X,O,X\n" +
			"E,X,E,X,O,O\n" +
			"E,X,E,O,E,E\n" +
			"E,X,E,O,E,X\n" +
			"E,X,E,O,E,O\n" +
			"E,X,E,O,X,E\n" +
			"E,X,E,O,X,X\n" +
			"E,X,E,O,X,O\n" +
			"E,X,E,O,O,E\n" +
			"E,X,E,O,O,X\n" +
			"E,X,E,O,O,O\n" +
			"E,X,X,E,E,E\n" +
			"E,X,X,E,E,X\n" +
			"E,X,X,E,E,O\n" +
			"E,X,X,E,X,E\n" +
			"E,X,X,E,X,X\n" +
			"E,X,X,E,X,O\n" +
			"E,X,X,E,O,E\n" +
			"E,X,X,E,O,X\n" +
			"E,X,X,E,O,O\n" +
			"E,X,X,X,E,E\n" +
			"E,X,X,X,E,X\n" +
			"E,X,X,X,E,O\n" +
			"E,X,X,X,X,E\n" +
			"E,X,X,X,X,X\n" +
			"E,X,X,X,X,O\n" +
			"E,X,X,X,O,E\n" +
			"E,X,X,X,O,X\n" +
			"E,X,X,X,O,O\n" +
			"E,X,X,O,E,E\n" +
			"E,X,X,O,E,X\n" +
			"E,X,X,O,E,O\n" +
			"E,X,X,O,X,E\n" +
			"E,X,X,O,X,X\n" +
			"E,X,X,O,X,O\n" +
			"E,X,X,O,O,E\n" +
			"E,X,X,O,O,X\n" +
			"E,X,X,O,O,O\n" +
			"E,X,O,E,E,E\n" +
			"E,X,O,E,E,X\n" +
			"E,X,O,E,E,O\n" +
			"E,X,O,E,X,E\n" +
			"E,X,O,E,X,X\n" +
			"E,X,O,E,X,O\n" +
			"E,X,O,E,O,E\n" +
			"E,X,O,E,O,X\n" +
			"E,X,O,E,O,O\n" +
			"E,X,O,X,E,E\n" +
			"E,X,O,X,E,X\n" +
			"E,X,O,X,E,O\n" +
			"E,X,O,X,X,E\n" +
			"E,X,O,X,X,X\n" +
			"E,X,O,X,X,O\n" +
			"E,X,O,X,O,E\n" +
			"E,X,O,X,O,X\n" +
			"E,X,O,X,O,O\n" +
			"E,X,O,O,E,E\n" +
			"E,X,O,O,E,X\n" +
			"E,X,O,O,E,O\n" +
			"E,X,O,O,X,E\n" +
			"E,X,O,O,X,X\n" +
			"E,X,O,O,X,O\n" +
			"E,X,O,O,O,E\n" +
			"E,X,O,O,O,X\n" +
			"E,X,O,O,O,O\n" +
			"E,O,E,E,E,E\n" +
			"E,O,E,E,E,X\n" +
			"E,O,E,E,E,O\n" +
			"E,O,E,E,X,E\n" +
			"E,O,E,E,X,X\n" +
			"E,O,E,E,X,O\n" +
			"E,O,E,E,O,E\n" +
			"E,O,E,E,O,X\n" +
			"E,O,E,E,O,O\n" +
			"E,O,E,X,E,E\n" +
			"E,O,E,X,E,X\n" +
			"E,O,E,X,E,O\n" +
			"E,O,E,X,X,E\n" +
			"E,O,E,X,X,X\n" +
			"E,O,E,X,X,O\n" +
			"E,O,E,X,O,E\n" +
			"E,O,E,X,O,X\n" +
			"E,O,E,X,O,O\n" +
			"E,O,E,O,E,E\n" +
			"E,O,E,O,E,X\n" +
			"E,O,E,O,E,O\n" +
			"E,O,E,O,X,E\n" +
			"E,O,E,O,X,X\n" +
			"E,O,E,O,X,O\n" +
			"E,O,E,O,O,E\n" +
			"E,O,E,O,O,X\n" +
			"E,O,E,O,O,O\n" +
			"E,O,X,E,E,E\n" +
			"E,O,X,E,E,X\n" +
			"E,O,X,E,E,O\n" +
			"E,O,X,E,X,E\n" +
			"E,O,X,E,X,X\n" +
			"E,O,X,E,X,O\n" +
			"E,O,X,E,O,E\n" +
			"E,O,X,E,O,X\n" +
			"E,O,X,E,O,O\n" +
			"E,O,X,X,E,E\n" +
			"E,O,X,X,E,X\n" +
			"E,O,X,X,E,O\n" +
			"E,O,X,X,X,E\n" +
			"E,O,X,X,X,X\n" +
			"E,O,X,X,X,O\n" +
			"E,O,X,X,O,E\n" +
			"E,O,X,X,O,X\n" +
			"E,O,X,X,O,O\n" +
			"E,O,X,O,E,E\n" +
			"E,O,X,O,E,X\n" +
			"E,O,X,O,E,O\n" +
			"E,O,X,O,X,E\n" +
			"E,O,X,O,X,X\n" +
			"E,O,X,O,X,O\n" +
			"E,O,X,O,O,E\n" +
			"E,O,X,O,O,X\n" +
			"E,O,X,O,O,O\n" +
			"E,O,O,E,E,E\n" +
			"E,O,O,E,E,X\n" +
			"E,O,O,E,E,O\n" +
			"E,O,O,E,X,E\n" +
			"E,O,O,E,X,X\n" +
			"E,O,O,E,X,O\n" +
			"E,O,O,E,O,E\n" +
			"E,O,O,E,O,X\n" +
			"E,O,O,E,O,O\n" +
			"E,O,O,X,E,E\n" +
			"E,O,O,X,E,X\n" +
			"E,O,O,X,E,O\n" +
			"E,O,O,X,X,E\n" +
			"E,O,O,X,X,X\n" +
			"E,O,O,X,X,O\n" +
			"E,O,O,X,O,E\n" +
			"E,O,O,X,O,X\n" +
			"E,O,O,X,O,O\n" +
			"E,O,O,O,E,E\n" +
			"E,O,O,O,E,X\n" +
			"E,O,O,O,E,O\n" +
			"E,O,O,O,X,E\n" +
			"E,O,O,O,X,X\n" +
			"E,O,O,O,X,O\n" +
			"E,O,O,O,O,E\n" +
			"E,O,O,O,O,X\n" +
			"E,O,O,O,O,O\n" +
			"X,E,E,E,E,E\n" +
			"X,E,E,E,E,X\n" +
			"X,E,E,E,E,O\n" +
			"X,E,E,E,X,E\n" +
			"X,E,E,E,X,X\n" +
			"X,E,E,E,X,O\n" +
			"X,E,E,E,O,E\n" +
			"X,E,E,E,O,X\n" +
			"X,E,E,E,O,O\n" +
			"X,E,E,X,E,E\n" +
			"X,E,E,X,E,X\n" +
			"X,E,E,X,E,O\n" +
			"X,E,E,X,X,E\n" +
			"X,E,E,X,X,X\n" +
			"X,E,E,X,X,O\n" +
			"X,E,E,X,O,E\n" +
			"X,E,E,X,O,X\n" +
			"X,E,E,X,O,O\n" +
			"X,E,E,O,E,E\n" +
			"X,E,E,O,E,X\n" +
			"X,E,E,O,E,O\n" +
			"X,E,E,O,X,E\n" +
			"X,E,E,O,X,X\n" +
			"X,E,E,O,X,O\n" +
			"X,E,E,O,O,E\n" +
			"X,E,E,O,O,X\n" +
			"X,E,E,O,O,O\n" +
			"X,E,X,E,E,E\n" +
			"X,E,X,E,E,X\n" +
			"X,E,X,E,E,O\n" +
			"X,E,X,E,X,E\n" +
			"X,E,X,E,X,X\n" +
			"X,E,X,E,X,O\n" +
			"X,E,X,E,O,E\n" +
			"X,E,X,E,O,X\n" +
			"X,E,X,E,O,O\n" +
			"X,E,X,X,E,E\n" +
			"X,E,X,X,E,X\n" +
			"X,E,X,X,E,O\n" +
			"X,E,X,X,X,E\n" +
			"X,E,X,X,X,X\n" +
			"X,E,X,X,X,O\n" +
			"X,E,X,X,O,E\n" +
			"X,E,X,X,O,X\n" +
			"X,E,X,X,O,O\n" +
			"X,E,X,O,E,E\n" +
			"X,E,X,O,E,X\n" +
			"X,E,X,O,E,O\n" +
			"X,E,X,O,X,E\n" +
			"X,E,X,O,X,X\n" +
			"X,E,X,O,X,O\n" +
			"X,E,X,O,O,E\n" +
			"X,E,X,O,O,X\n" +
			"X,E,X,O,O,O\n" +
			"X,E,O,E,E,E\n" +
			"X,E,O,E,E,X\n" +
			"X,E,O,E,E,O\n" +
			"X,E,O,E,X,E\n" +
			"X,E,O,E,X,X\n" +
			"X,E,O,E,X,O\n" +
			"X,E,O,E,O,E\n" +
			"X,E,O,E,O,X\n" +
			"X,E,O,E,O,O\n" +
			"X,E,O,X,E,E\n" +
			"X,E,O,X,E,X\n" +
			"X,E,O,X,E,O\n" +
			"X,E,O,X,X,E\n" +
			"X,E,O,X,X,X\n" +
			"X,E,O,X,X,O\n" +
			"X,E,O,X,O,E\n" +
			"X,E,O,X,O,X\n" +
			"X,E,O,X,O,O\n" +
			"X,E,O,O,E,E\n" +
			"X,E,O,O,E,X\n" +
			"X,E,O,O,E,O\n" +
			"X,E,O,O,X,E\n" +
			"X,E,O,O,X,X\n" +
			"X,E,O,O,X,O\n" +
			"X,E,O,O,O,E\n" +
			"X,E,O,O,O,X\n" +
			"X,E,O,O,O,O\n" +
			"X,X,E,E,E,E\n" +
			"X,X,E,E,E,X\n" +
			"X,X,E,E,E,O\n" +
			"X,X,E,E,X,E\n" +
			"X,X,E,E,X,X\n" +
			"X,X,E,E,X,O\n" +
			"X,X,E,E,O,E\n" +
			"X,X,E,E,O,X\n" +
			"X,X,E,E,O,O\n" +
			"X,X,E,X,E,E\n" +
			"X,X,E,X,E,X\n" +
			"X,X,E,X,E,O\n" +
			"X,X,E,X,X,E\n" +
			"X,X,E,X,X,X\n" +
			"X,X,E,X,X,O\n" +
			"X,X,E,X,O,E\n" +
			"X,X,E,X,O,X\n" +
			"X,X,E,X,O,O\n" +
			"X,X,E,O,E,E\n" +
			"X,X,E,O,E,X\n" +
			"X,X,E,O,E,O\n" +
			"X,X,E,O,X,E\n" +
			"X,X,E,O,X,X\n" +
			"X,X,E,O,X,O\n" +
			"X,X,E,O,O,E\n" +
			"X,X,E,O,O,X\n" +
			"X,X,E,O,O,O\n" +
			"X,X,X,E,E,E\n" +
			"X,X,X,E,E,X\n" +
			"X,X,X,E,E,O\n" +
			"X,X,X,E,X,E\n" +
			"X,X,X,E,X,X\n" +
			"X,X,X,E,X,O\n" +
			"X,X,X,E,O,E\n" +
			"X,X,X,E,O,X\n" +
			"X,X,X,E,O,O\n" +
			"X,X,X,X,E,E\n" +
			"X,X,X,X,E,X\n" +
			"X,X,X,X,E,O\n" +
			"X,X,X,X,X,E\n" +
			"X,X,X,X,X,X\n" +
			"X,X,X,X,X,O\n" +
			"X,X,X,X,O,E\n" +
			"X,X,X,X,O,X\n" +
			"X,X,X,X,O,O\n" +
			"X,X,X,O,E,E\n" +
			"X,X,X,O,E,X\n" +
			"X,X,X,O,E,O\n" +
			"X,X,X,O,X,E\n" +
			"X,X,X,O,X,X\n" +
			"X,X,X,O,X,O\n" +
			"X,X,X,O,O,E\n" +
			"X,X,X,O,O,X\n" +
			"X,X,X,O,O,O\n" +
			"X,X,O,E,E,E\n" +
			"X,X,O,E,E,X\n" +
			"X,X,O,E,E,O\n" +
			"X,X,O,E,X,E\n" +
			"X,X,O,E,X,X\n" +
			"X,X,O,E,X,O\n" +
			"X,X,O,E,O,E\n" +
			"X,X,O,E,O,X\n" +
			"X,X,O,E,O,O\n" +
			"X,X,O,X,E,E\n" +
			"X,X,O,X,E,X\n" +
			"X,X,O,X,E,O\n" +
			"X,X,O,X,X,E\n" +
			"X,X,O,X,X,X\n" +
			"X,X,O,X,X,O\n" +
			"X,X,O,X,O,E\n" +
			"X,X,O,X,O,X\n" +
			"X,X,O,X,O,O\n" +
			"X,X,O,O,E,E\n" +
			"X,X,O,O,E,X\n" +
			"X,X,O,O,E,O\n" +
			"X,X,O,O,X,E\n" +
			"X,X,O,O,X,X\n" +
			"X,X,O,O,X,O\n" +
			"X,X,O,O,O,E\n" +
			"X,X,O,O,O,X\n" +
			"X,X,O,O,O,O\n" +
			"X,O,E,E,E,E\n" +
			"X,O,E,E,E,X\n" +
			"X,O,E,E,E,O\n" +
			"X,O,E,E,X,E\n" +
			"X,O,E,E,X,X\n" +
			"X,O,E,E,X,O\n" +
			"X,O,E,E,O,E\n" +
			"X,O,E,E,O,X\n" +
			"X,O,E,E,O,O\n" +
			"X,O,E,X,E,E\n" +
			"X,O,E,X,E,X\n" +
			"X,O,E,X,E,O\n" +
			"X,O,E,X,X,E\n" +
			"X,O,E,X,X,X\n" +
			"X,O,E,X,X,O\n" +
			"X,O,E,X,O,E\n" +
			"X,O,E,X,O,X\n" +
			"X,O,E,X,O,O\n" +
			"X,O,E,O,E,E\n" +
			"X,O,E,O,E,X\n" +
			"X,O,E,O,E,O\n" +
			"X,O,E,O,X,E\n" +
			"X,O,E,O,X,X\n" +
			"X,O,E,O,X,O\n" +
			"X,O,E,O,O,E\n" +
			"X,O,E,O,O,X\n" +
			"X,O,E,O,O,O\n" +
			"X,O,X,E,E,E\n" +
			"X,O,X,E,E,X\n" +
			"X,O,X,E,E,O\n" +
			"X,O,X,E,X,E\n" +
			"X,O,X,E,X,X\n" +
			"X,O,X,E,X,O\n" +
			"X,O,X,E,O,E\n" +
			"X,O,X,E,O,X\n" +
			"X,O,X,E,O,O\n" +
			"X,O,X,X,E,E\n" +
			"X,O,X,X,E,X\n" +
			"X,O,X,X,E,O\n" +
			"X,O,X,X,X,E\n" +
			"X,O,X,X,X,X\n" +
			"X,O,X,X,X,O\n" +
			"X,O,X,X,O,E\n" +
			"X,O,X,X,O,X\n" +
			"X,O,X,X,O,O\n" +
			"X,O,X,O,E,E\n" +
			"X,O,X,O,E,X\n" +
			"X,O,X,O,E,O\n" +
			"X,O,X,O,X,E\n" +
			"X,O,X,O,X,X\n" +
			"X,O,X,O,X,O\n" +
			"X,O,X,O,O,E\n" +
			"X,O,X,O,O,X\n" +
			"X,O,X,O,O,O\n" +
			"X,O,O,E,E,E\n" +
			"X,O,O,E,E,X\n" +
			"X,O,O,E,E,O\n" +
			"X,O,O,E,X,E\n" +
			"X,O,O,E,X,X\n" +
			"X,O,O,E,X,O\n" +
			"X,O,O,E,O,E\n" +
			"X,O,O,E,O,X\n" +
			"X,O,O,E,O,O\n" +
			"X,O,O,X,E,E\n" +
			"X,O,O,X,E,X\n" +
			"X,O,O,X,E,O\n" +
			"X,O,O,X,X,E\n" +
			"X,O,O,X,X,X\n" +
			"X,O,O,X,X,O\n" +
			"X,O,O,X,O,E\n" +
			"X,O,O,X,O,X\n" +
			"X,O,O,X,O,O\n" +
			"X,O,O,O,E,E\n" +
			"X,O,O,O,E,X\n" +
			"X,O,O,O,E,O\n" +
			"X,O,O,O,X,E\n" +
			"X,O,O,O,X,X\n" +
			"X,O,O,O,X,O\n" +
			"X,O,O,O,O,E\n" +
			"X,O,O,O,O,X\n" +
			"X,O,O,O,O,O\n" +
			"O,E,E,E,E,E\n" +
			"O,E,E,E,E,X\n" +
			"O,E,E,E,E,O\n" +
			"O,E,E,E,X,E\n" +
			"O,E,E,E,X,X\n" +
			"O,E,E,E,X,O\n" +
			"O,E,E,E,O,E\n" +
			"O,E,E,E,O,X\n" +
			"O,E,E,E,O,O\n" +
			"O,E,E,X,E,E\n" +
			"O,E,E,X,E,X\n" +
			"O,E,E,X,E,O\n" +
			"O,E,E,X,X,E\n" +
			"O,E,E,X,X,X\n" +
			"O,E,E,X,X,O\n" +
			"O,E,E,X,O,E\n" +
			"O,E,E,X,O,X\n" +
			"O,E,E,X,O,O\n" +
			"O,E,E,O,E,E\n" +
			"O,E,E,O,E,X\n" +
			"O,E,E,O,E,O\n" +
			"O,E,E,O,X,E\n" +
			"O,E,E,O,X,X\n" +
			"O,E,E,O,X,O\n" +
			"O,E,E,O,O,E\n" +
			"O,E,E,O,O,X\n" +
			"O,E,E,O,O,O\n" +
			"O,E,X,E,E,E\n" +
			"O,E,X,E,E,X\n" +
			"O,E,X,E,E,O\n" +
			"O,E,X,E,X,E\n" +
			"O,E,X,E,X,X\n" +
			"O,E,X,E,X,O\n" +
			"O,E,X,E,O,E\n" +
			"O,E,X,E,O,X\n" +
			"O,E,X,E,O,O\n" +
			"O,E,X,X,E,E\n" +
			"O,E,X,X,E,X\n" +
			"O,E,X,X,E,O\n" +
			"O,E,X,X,X,E\n" +
			"O,E,X,X,X,X\n" +
			"O,E,X,X,X,O\n" +
			"O,E,X,X,O,E\n" +
			"O,E,X,X,O,X\n" +
			"O,E,X,X,O,O\n" +
			"O,E,X,O,E,E\n" +
			"O,E,X,O,E,X\n" +
			"O,E,X,O,E,O\n" +
			"O,E,X,O,X,E\n" +
			"O,E,X,O,X,X\n" +
			"O,E,X,O,X,O\n" +
			"O,E,X,O,O,E\n" +
			"O,E,X,O,O,X\n" +
			"O,E,X,O,O,O\n" +
			"O,E,O,E,E,E\n" +
			"O,E,O,E,E,X\n" +
			"O,E,O,E,E,O\n" +
			"O,E,O,E,X,E\n" +
			"O,E,O,E,X,X\n" +
			"O,E,O,E,X,O\n" +
			"O,E,O,E,O,E\n" +
			"O,E,O,E,O,X\n" +
			"O,E,O,E,O,O\n" +
			"O,E,O,X,E,E\n" +
			"O,E,O,X,E,X\n" +
			"O,E,O,X,E,O\n" +
			"O,E,O,X,X,E\n" +
			"O,E,O,X,X,X\n" +
			"O,E,O,X,X,O\n" +
			"O,E,O,X,O,E\n" +
			"O,E,O,X,O,X\n" +
			"O,E,O,X,O,O\n" +
			"O,E,O,O,E,E\n" +
			"O,E,O,O,E,X\n" +
			"O,E,O,O,E,O\n" +
			"O,E,O,O,X,E\n" +
			"O,E,O,O,X,X\n" +
			"O,E,O,O,X,O\n" +
			"O,E,O,O,O,E\n" +
			"O,E,O,O,O,X\n" +
			"O,E,O,O,O,O\n" +
			"O,X,E,E,E,E\n" +
			"O,X,E,E,E,X\n" +
			"O,X,E,E,E,O\n" +
			"O,X,E,E,X,E\n" +
			"O,X,E,E,X,X\n" +
			"O,X,E,E,X,O\n" +
			"O,X,E,E,O,E\n" +
			"O,X,E,E,O,X\n" +
			"O,X,E,E,O,O\n" +
			"O,X,E,X,E,E\n" +
			"O,X,E,X,E,X\n" +
			"O,X,E,X,E,O\n" +
			"O,X,E,X,X,E\n" +
			"O,X,E,X,X,X\n" +
			"O,X,E,X,X,O\n" +
			"O,X,E,X,O,E\n" +
			"O,X,E,X,O,X\n" +
			"O,X,E,X,O,O\n" +
			"O,X,E,O,E,E\n" +
			"O,X,E,O,E,X\n" +
			"O,X,E,O,E,O\n" +
			"O,X,E,O,X,E\n" +
			"O,X,E,O,X,X\n" +
			"O,X,E,O,X,O\n" +
			"O,X,E,O,O,E\n" +
			"O,X,E,O,O,X\n" +
			"O,X,E,O,O,O\n" +
			"O,X,X,E,E,E\n" +
			"O,X,X,E,E,X\n" +
			"O,X,X,E,E,O\n" +
			"O,X,X,E,X,E\n" +
			"O,X,X,E,X,X\n" +
			"O,X,X,E,X,O\n" +
			"O,X,X,E,O,E\n" +
			"O,X,X,E,O,X\n" +
			"O,X,X,E,O,O\n" +
			"O,X,X,X,E,E\n" +
			"O,X,X,X,E,X\n" +
			"O,X,X,X,E,O\n" +
			"O,X,X,X,X,E\n" +
			"O,X,X,X,X,X\n" +
			"O,X,X,X,X,O\n" +
			"O,X,X,X,O,E\n" +
			"O,X,X,X,O,X\n" +
			"O,X,X,X,O,O\n" +
			"O,X,X,O,E,E\n" +
			"O,X,X,O,E,X\n" +
			"O,X,X,O,E,O\n" +
			"O,X,X,O,X,E\n" +
			"O,X,X,O,X,X\n" +
			"O,X,X,O,X,O\n" +
			"O,X,X,O,O,E\n" +
			"O,X,X,O,O,X\n" +
			"O,X,X,O,O,O\n" +
			"O,X,O,E,E,E\n" +
			"O,X,O,E,E,X\n" +
			"O,X,O,E,E,O\n" +
			"O,X,O,E,X,E\n" +
			"O,X,O,E,X,X\n" +
			"O,X,O,E,X,O\n" +
			"O,X,O,E,O,E\n" +
			"O,X,O,E,O,X\n" +
			"O,X,O,E,O,O\n" +
			"O,X,O,X,E,E\n" +
			"O,X,O,X,E,X\n" +
			"O,X,O,X,E,O\n" +
			"O,X,O,X,X,E\n" +
			"O,X,O,X,X,X\n" +
			"O,X,O,X,X,O\n" +
			"O,X,O,X,O,E\n" +
			"O,X,O,X,O,X\n" +
			"O,X,O,X,O,O\n" +
			"O,X,O,O,E,E\n" +
			"O,X,O,O,E,X\n" +
			"O,X,O,O,E,O\n" +
			"O,X,O,O,X,E\n" +
			"O,X,O,O,X,X\n" +
			"O,X,O,O,X,O\n" +
			"O,X,O,O,O,E\n" +
			"O,X,O,O,O,X\n" +
			"O,X,O,O,O,O\n" +
			"O,O,E,E,E,E\n" +
			"O,O,E,E,E,X\n" +
			"O,O,E,E,E,O\n" +
			"O,O,E,E,X,E\n" +
			"O,O,E,E,X,X\n" +
			"O,O,E,E,X,O\n" +
			"O,O,E,E,O,E\n" +
			"O,O,E,E,O,X\n" +
			"O,O,E,E,O,O\n" +
			"O,O,E,X,E,E\n" +
			"O,O,E,X,E,X\n" +
			"O,O,E,X,E,O\n" +
			"O,O,E,X,X,E\n" +
			"O,O,E,X,X,X\n" +
			"O,O,E,X,X,O\n" +
			"O,O,E,X,O,E\n" +
			"O,O,E,X,O,X\n" +
			"O,O,E,X,O,O\n" +
			"O,O,E,O,E,E\n" +
			"O,O,E,O,E,X\n" +
			"O,O,E,O,E,O\n" +
			"O,O,E,O,X,E\n" +
			"O,O,E,O,X,X\n" +
			"O,O,E,O,X,O\n" +
			"O,O,E,O,O,E\n" +
			"O,O,E,O,O,X\n" +
			"O,O,E,O,O,O\n" +
			"O,O,X,E,E,E\n" +
			"O,O,X,E,E,X\n" +
			"O,O,X,E,E,O\n" +
			"O,O,X,E,X,E\n" +
			"O,O,X,E,X,X\n" +
			"O,O,X,E,X,O\n" +
			"O,O,X,E,O,E\n" +
			"O,O,X,E,O,X\n" +
			"O,O,X,E,O,O\n" +
			"O,O,X,X,E,E\n" +
			"O,O,X,X,E,X\n" +
			"O,O,X,X,E,O\n" +
			"O,O,X,X,X,E\n" +
			"O,O,X,X,X,X\n" +
			"O,O,X,X,X,O\n" +
			"O,O,X,X,O,E\n" +
			"O,O,X,X,O,X\n" +
			"O,O,X,X,O,O\n" +
			"O,O,X,O,E,E\n" +
			"O,O,X,O,E,X\n" +
			"O,O,X,O,E,O\n" +
			"O,O,X,O,X,E\n" +
			"O,O,X,O,X,X\n" +
			"O,O,X,O,X,O\n" +
			"O,O,X,O,O,E\n" +
			"O,O,X,O,O,X\n" +
			"O,O,X,O,O,O\n" +
			"O,O,O,E,E,E\n" +
			"O,O,O,E,E,X\n" +
			"O,O,O,E,E,O\n" +
			"O,O,O,E,X,E\n" +
			"O,O,O,E,X,X\n" +
			"O,O,O,E,X,O\n" +
			"O,O,O,E,O,E\n" +
			"O,O,O,E,O,X\n" +
			"O,O,O,E,O,O\n" +
			"O,O,O,X,E,E\n" +
			"O,O,O,X,E,X\n" +
			"O,O,O,X,E,O\n" +
			"O,O,O,X,X,E\n" +
			"O,O,O,X,X,X\n" +
			"O,O,O,X,X,O\n" +
			"O,O,O,X,O,E\n" +
			"O,O,O,X,O,X\n" +
			"O,O,O,X,O,O\n" +
			"O,O,O,O,E,E\n" +
			"O,O,O,O,E,X\n" +
			"O,O,O,O,E,O\n" +
			"O,O,O,O,X,E\n" +
			"O,O,O,O,X,X\n" +
			"O,O,O,O,X,O\n" +
			"O,O,O,O,O,E\n" +
			"O,O,O,O,O,X\n" +
			"O,O,O,O,O,O\n"
		);

        String hash_7 =
		(
			"E,E,E,E,E,E,E\n" +
			"E,E,E,E,E,E,X\n" +
			"E,E,E,E,E,E,O\n" +
			"E,E,E,E,E,X,E\n" +
			"E,E,E,E,E,X,X\n" +
			"E,E,E,E,E,X,O\n" +
			"E,E,E,E,E,O,E\n" +
			"E,E,E,E,E,O,X\n" +
			"E,E,E,E,E,O,O\n" +
			"E,E,E,E,X,E,E\n" +
			"E,E,E,E,X,E,X\n" +
			"E,E,E,E,X,E,O\n" +
			"E,E,E,E,X,X,E\n" +
			"E,E,E,E,X,X,X\n" +
			"E,E,E,E,X,X,O\n" +
			"E,E,E,E,X,O,E\n" +
			"E,E,E,E,X,O,X\n" +
			"E,E,E,E,X,O,O\n" +
			"E,E,E,E,O,E,E\n" +
			"E,E,E,E,O,E,X\n" +
			"E,E,E,E,O,E,O\n" +
			"E,E,E,E,O,X,E\n" +
			"E,E,E,E,O,X,X\n" +
			"E,E,E,E,O,X,O\n" +
			"E,E,E,E,O,O,E\n" +
			"E,E,E,E,O,O,X\n" +
			"E,E,E,E,O,O,O\n" +
			"E,E,E,X,E,E,E\n" +
			"E,E,E,X,E,E,X\n" +
			"E,E,E,X,E,E,O\n" +
			"E,E,E,X,E,X,E\n" +
			"E,E,E,X,E,X,X\n" +
			"E,E,E,X,E,X,O\n" +
			"E,E,E,X,E,O,E\n" +
			"E,E,E,X,E,O,X\n" +
			"E,E,E,X,E,O,O\n" +
			"E,E,E,X,X,E,E\n" +
			"E,E,E,X,X,E,X\n" +
			"E,E,E,X,X,E,O\n" +
			"E,E,E,X,X,X,E\n" +
			"E,E,E,X,X,X,X\n" +
			"E,E,E,X,X,X,O\n" +
			"E,E,E,X,X,O,E\n" +
			"E,E,E,X,X,O,X\n" +
			"E,E,E,X,X,O,O\n" +
			"E,E,E,X,O,E,E\n" +
			"E,E,E,X,O,E,X\n" +
			"E,E,E,X,O,E,O\n" +
			"E,E,E,X,O,X,E\n" +
			"E,E,E,X,O,X,X\n" +
			"E,E,E,X,O,X,O\n" +
			"E,E,E,X,O,O,E\n" +
			"E,E,E,X,O,O,X\n" +
			"E,E,E,X,O,O,O\n" +
			"E,E,E,O,E,E,E\n" +
			"E,E,E,O,E,E,X\n" +
			"E,E,E,O,E,E,O\n" +
			"E,E,E,O,E,X,E\n" +
			"E,E,E,O,E,X,X\n" +
			"E,E,E,O,E,X,O\n" +
			"E,E,E,O,E,O,E\n" +
			"E,E,E,O,E,O,X\n" +
			"E,E,E,O,E,O,O\n" +
			"E,E,E,O,X,E,E\n" +
			"E,E,E,O,X,E,X\n" +
			"E,E,E,O,X,E,O\n" +
			"E,E,E,O,X,X,E\n" +
			"E,E,E,O,X,X,X\n" +
			"E,E,E,O,X,X,O\n" +
			"E,E,E,O,X,O,E\n" +
			"E,E,E,O,X,O,X\n" +
			"E,E,E,O,X,O,O\n" +
			"E,E,E,O,O,E,E\n" +
			"E,E,E,O,O,E,X\n" +
			"E,E,E,O,O,E,O\n" +
			"E,E,E,O,O,X,E\n" +
			"E,E,E,O,O,X,X\n" +
			"E,E,E,O,O,X,O\n" +
			"E,E,E,O,O,O,E\n" +
			"E,E,E,O,O,O,X\n" +
			"E,E,E,O,O,O,O\n" +
			"E,E,X,E,E,E,E\n" +
			"E,E,X,E,E,E,X\n" +
			"E,E,X,E,E,E,O\n" +
			"E,E,X,E,E,X,E\n" +
			"E,E,X,E,E,X,X\n" +
			"E,E,X,E,E,X,O\n" +
			"E,E,X,E,E,O,E\n" +
			"E,E,X,E,E,O,X\n" +
			"E,E,X,E,E,O,O\n" +
			"E,E,X,E,X,E,E\n" +
			"E,E,X,E,X,E,X\n" +
			"E,E,X,E,X,E,O\n" +
			"E,E,X,E,X,X,E\n" +
			"E,E,X,E,X,X,X\n" +
			"E,E,X,E,X,X,O\n" +
			"E,E,X,E,X,O,E\n" +
			"E,E,X,E,X,O,X\n" +
			"E,E,X,E,X,O,O\n" +
			"E,E,X,E,O,E,E\n" +
			"E,E,X,E,O,E,X\n" +
			"E,E,X,E,O,E,O\n" +
			"E,E,X,E,O,X,E\n" +
			"E,E,X,E,O,X,X\n" +
			"E,E,X,E,O,X,O\n" +
			"E,E,X,E,O,O,E\n" +
			"E,E,X,E,O,O,X\n" +
			"E,E,X,E,O,O,O\n" +
			"E,E,X,X,E,E,E\n" +
			"E,E,X,X,E,E,X\n" +
			"E,E,X,X,E,E,O\n" +
			"E,E,X,X,E,X,E\n" +
			"E,E,X,X,E,X,X\n" +
			"E,E,X,X,E,X,O\n" +
			"E,E,X,X,E,O,E\n" +
			"E,E,X,X,E,O,X\n" +
			"E,E,X,X,E,O,O\n" +
			"E,E,X,X,X,E,E\n" +
			"E,E,X,X,X,E,X\n" +
			"E,E,X,X,X,E,O\n" +
			"E,E,X,X,X,X,E\n" +
			"E,E,X,X,X,X,X\n" +
			"E,E,X,X,X,X,O\n" +
			"E,E,X,X,X,O,E\n" +
			"E,E,X,X,X,O,X\n" +
			"E,E,X,X,X,O,O\n" +
			"E,E,X,X,O,E,E\n" +
			"E,E,X,X,O,E,X\n" +
			"E,E,X,X,O,E,O\n" +
			"E,E,X,X,O,X,E\n" +
			"E,E,X,X,O,X,X\n" +
			"E,E,X,X,O,X,O\n" +
			"E,E,X,X,O,O,E\n" +
			"E,E,X,X,O,O,X\n" +
			"E,E,X,X,O,O,O\n" +
			"E,E,X,O,E,E,E\n" +
			"E,E,X,O,E,E,X\n" +
			"E,E,X,O,E,E,O\n" +
			"E,E,X,O,E,X,E\n" +
			"E,E,X,O,E,X,X\n" +
			"E,E,X,O,E,X,O\n" +
			"E,E,X,O,E,O,E\n" +
			"E,E,X,O,E,O,X\n" +
			"E,E,X,O,E,O,O\n" +
			"E,E,X,O,X,E,E\n" +
			"E,E,X,O,X,E,X\n" +
			"E,E,X,O,X,E,O\n" +
			"E,E,X,O,X,X,E\n" +
			"E,E,X,O,X,X,X\n" +
			"E,E,X,O,X,X,O\n" +
			"E,E,X,O,X,O,E\n" +
			"E,E,X,O,X,O,X\n" +
			"E,E,X,O,X,O,O\n" +
			"E,E,X,O,O,E,E\n" +
			"E,E,X,O,O,E,X\n" +
			"E,E,X,O,O,E,O\n" +
			"E,E,X,O,O,X,E\n" +
			"E,E,X,O,O,X,X\n" +
			"E,E,X,O,O,X,O\n" +
			"E,E,X,O,O,O,E\n" +
			"E,E,X,O,O,O,X\n" +
			"E,E,X,O,O,O,O\n" +
			"E,E,O,E,E,E,E\n" +
			"E,E,O,E,E,E,X\n" +
			"E,E,O,E,E,E,O\n" +
			"E,E,O,E,E,X,E\n" +
			"E,E,O,E,E,X,X\n" +
			"E,E,O,E,E,X,O\n" +
			"E,E,O,E,E,O,E\n" +
			"E,E,O,E,E,O,X\n" +
			"E,E,O,E,E,O,O\n" +
			"E,E,O,E,X,E,E\n" +
			"E,E,O,E,X,E,X\n" +
			"E,E,O,E,X,E,O\n" +
			"E,E,O,E,X,X,E\n" +
			"E,E,O,E,X,X,X\n" +
			"E,E,O,E,X,X,O\n" +
			"E,E,O,E,X,O,E\n" +
			"E,E,O,E,X,O,X\n" +
			"E,E,O,E,X,O,O\n" +
			"E,E,O,E,O,E,E\n" +
			"E,E,O,E,O,E,X\n" +
			"E,E,O,E,O,E,O\n" +
			"E,E,O,E,O,X,E\n" +
			"E,E,O,E,O,X,X\n" +
			"E,E,O,E,O,X,O\n" +
			"E,E,O,E,O,O,E\n" +
			"E,E,O,E,O,O,X\n" +
			"E,E,O,E,O,O,O\n" +
			"E,E,O,X,E,E,E\n" +
			"E,E,O,X,E,E,X\n" +
			"E,E,O,X,E,E,O\n" +
			"E,E,O,X,E,X,E\n" +
			"E,E,O,X,E,X,X\n" +
			"E,E,O,X,E,X,O\n" +
			"E,E,O,X,E,O,E\n" +
			"E,E,O,X,E,O,X\n" +
			"E,E,O,X,E,O,O\n" +
			"E,E,O,X,X,E,E\n" +
			"E,E,O,X,X,E,X\n" +
			"E,E,O,X,X,E,O\n" +
			"E,E,O,X,X,X,E\n" +
			"E,E,O,X,X,X,X\n" +
			"E,E,O,X,X,X,O\n" +
			"E,E,O,X,X,O,E\n" +
			"E,E,O,X,X,O,X\n" +
			"E,E,O,X,X,O,O\n" +
			"E,E,O,X,O,E,E\n" +
			"E,E,O,X,O,E,X\n" +
			"E,E,O,X,O,E,O\n" +
			"E,E,O,X,O,X,E\n" +
			"E,E,O,X,O,X,X\n" +
			"E,E,O,X,O,X,O\n" +
			"E,E,O,X,O,O,E\n" +
			"E,E,O,X,O,O,X\n" +
			"E,E,O,X,O,O,O\n" +
			"E,E,O,O,E,E,E\n" +
			"E,E,O,O,E,E,X\n" +
			"E,E,O,O,E,E,O\n" +
			"E,E,O,O,E,X,E\n" +
			"E,E,O,O,E,X,X\n" +
			"E,E,O,O,E,X,O\n" +
			"E,E,O,O,E,O,E\n" +
			"E,E,O,O,E,O,X\n" +
			"E,E,O,O,E,O,O\n" +
			"E,E,O,O,X,E,E\n" +
			"E,E,O,O,X,E,X\n" +
			"E,E,O,O,X,E,O\n" +
			"E,E,O,O,X,X,E\n" +
			"E,E,O,O,X,X,X\n" +
			"E,E,O,O,X,X,O\n" +
			"E,E,O,O,X,O,E\n" +
			"E,E,O,O,X,O,X\n" +
			"E,E,O,O,X,O,O\n" +
			"E,E,O,O,O,E,E\n" +
			"E,E,O,O,O,E,X\n" +
			"E,E,O,O,O,E,O\n" +
			"E,E,O,O,O,X,E\n" +
			"E,E,O,O,O,X,X\n" +
			"E,E,O,O,O,X,O\n" +
			"E,E,O,O,O,O,E\n" +
			"E,E,O,O,O,O,X\n" +
			"E,E,O,O,O,O,O\n" +
			"E,X,E,E,E,E,E\n" +
			"E,X,E,E,E,E,X\n" +
			"E,X,E,E,E,E,O\n" +
			"E,X,E,E,E,X,E\n" +
			"E,X,E,E,E,X,X\n" +
			"E,X,E,E,E,X,O\n" +
			"E,X,E,E,E,O,E\n" +
			"E,X,E,E,E,O,X\n" +
			"E,X,E,E,E,O,O\n" +
			"E,X,E,E,X,E,E\n" +
			"E,X,E,E,X,E,X\n" +
			"E,X,E,E,X,E,O\n" +
			"E,X,E,E,X,X,E\n" +
			"E,X,E,E,X,X,X\n" +
			"E,X,E,E,X,X,O\n" +
			"E,X,E,E,X,O,E\n" +
			"E,X,E,E,X,O,X\n" +
			"E,X,E,E,X,O,O\n" +
			"E,X,E,E,O,E,E\n" +
			"E,X,E,E,O,E,X\n" +
			"E,X,E,E,O,E,O\n" +
			"E,X,E,E,O,X,E\n" +
			"E,X,E,E,O,X,X\n" +
			"E,X,E,E,O,X,O\n" +
			"E,X,E,E,O,O,E\n" +
			"E,X,E,E,O,O,X\n" +
			"E,X,E,E,O,O,O\n" +
			"E,X,E,X,E,E,E\n" +
			"E,X,E,X,E,E,X\n" +
			"E,X,E,X,E,E,O\n" +
			"E,X,E,X,E,X,E\n" +
			"E,X,E,X,E,X,X\n" +
			"E,X,E,X,E,X,O\n" +
			"E,X,E,X,E,O,E\n" +
			"E,X,E,X,E,O,X\n" +
			"E,X,E,X,E,O,O\n" +
			"E,X,E,X,X,E,E\n" +
			"E,X,E,X,X,E,X\n" +
			"E,X,E,X,X,E,O\n" +
			"E,X,E,X,X,X,E\n" +
			"E,X,E,X,X,X,X\n" +
			"E,X,E,X,X,X,O\n" +
			"E,X,E,X,X,O,E\n" +
			"E,X,E,X,X,O,X\n" +
			"E,X,E,X,X,O,O\n" +
			"E,X,E,X,O,E,E\n" +
			"E,X,E,X,O,E,X\n" +
			"E,X,E,X,O,E,O\n" +
			"E,X,E,X,O,X,E\n" +
			"E,X,E,X,O,X,X\n" +
			"E,X,E,X,O,X,O\n" +
			"E,X,E,X,O,O,E\n" +
			"E,X,E,X,O,O,X\n" +
			"E,X,E,X,O,O,O\n" +
			"E,X,E,O,E,E,E\n" +
			"E,X,E,O,E,E,X\n" +
			"E,X,E,O,E,E,O\n" +
			"E,X,E,O,E,X,E\n" +
			"E,X,E,O,E,X,X\n" +
			"E,X,E,O,E,X,O\n" +
			"E,X,E,O,E,O,E\n" +
			"E,X,E,O,E,O,X\n" +
			"E,X,E,O,E,O,O\n" +
			"E,X,E,O,X,E,E\n" +
			"E,X,E,O,X,E,X\n" +
			"E,X,E,O,X,E,O\n" +
			"E,X,E,O,X,X,E\n" +
			"E,X,E,O,X,X,X\n" +
			"E,X,E,O,X,X,O\n" +
			"E,X,E,O,X,O,E\n" +
			"E,X,E,O,X,O,X\n" +
			"E,X,E,O,X,O,O\n" +
			"E,X,E,O,O,E,E\n" +
			"E,X,E,O,O,E,X\n" +
			"E,X,E,O,O,E,O\n" +
			"E,X,E,O,O,X,E\n" +
			"E,X,E,O,O,X,X\n" +
			"E,X,E,O,O,X,O\n" +
			"E,X,E,O,O,O,E\n" +
			"E,X,E,O,O,O,X\n" +
			"E,X,E,O,O,O,O\n" +
			"E,X,X,E,E,E,E\n" +
			"E,X,X,E,E,E,X\n" +
			"E,X,X,E,E,E,O\n" +
			"E,X,X,E,E,X,E\n" +
			"E,X,X,E,E,X,X\n" +
			"E,X,X,E,E,X,O\n" +
			"E,X,X,E,E,O,E\n" +
			"E,X,X,E,E,O,X\n" +
			"E,X,X,E,E,O,O\n" +
			"E,X,X,E,X,E,E\n" +
			"E,X,X,E,X,E,X\n" +
			"E,X,X,E,X,E,O\n" +
			"E,X,X,E,X,X,E\n" +
			"E,X,X,E,X,X,X\n" +
			"E,X,X,E,X,X,O\n" +
			"E,X,X,E,X,O,E\n" +
			"E,X,X,E,X,O,X\n" +
			"E,X,X,E,X,O,O\n" +
			"E,X,X,E,O,E,E\n" +
			"E,X,X,E,O,E,X\n" +
			"E,X,X,E,O,E,O\n" +
			"E,X,X,E,O,X,E\n" +
			"E,X,X,E,O,X,X\n" +
			"E,X,X,E,O,X,O\n" +
			"E,X,X,E,O,O,E\n" +
			"E,X,X,E,O,O,X\n" +
			"E,X,X,E,O,O,O\n" +
			"E,X,X,X,E,E,E\n" +
			"E,X,X,X,E,E,X\n" +
			"E,X,X,X,E,E,O\n" +
			"E,X,X,X,E,X,E\n" +
			"E,X,X,X,E,X,X\n" +
			"E,X,X,X,E,X,O\n" +
			"E,X,X,X,E,O,E\n" +
			"E,X,X,X,E,O,X\n" +
			"E,X,X,X,E,O,O\n" +
			"E,X,X,X,X,E,E\n" +
			"E,X,X,X,X,E,X\n" +
			"E,X,X,X,X,E,O\n" +
			"E,X,X,X,X,X,E\n" +
			"E,X,X,X,X,X,X\n" +
			"E,X,X,X,X,X,O\n" +
			"E,X,X,X,X,O,E\n" +
			"E,X,X,X,X,O,X\n" +
			"E,X,X,X,X,O,O\n" +
			"E,X,X,X,O,E,E\n" +
			"E,X,X,X,O,E,X\n" +
			"E,X,X,X,O,E,O\n" +
			"E,X,X,X,O,X,E\n" +
			"E,X,X,X,O,X,X\n" +
			"E,X,X,X,O,X,O\n" +
			"E,X,X,X,O,O,E\n" +
			"E,X,X,X,O,O,X\n" +
			"E,X,X,X,O,O,O\n" +
			"E,X,X,O,E,E,E\n" +
			"E,X,X,O,E,E,X\n" +
			"E,X,X,O,E,E,O\n" +
			"E,X,X,O,E,X,E\n" +
			"E,X,X,O,E,X,X\n" +
			"E,X,X,O,E,X,O\n" +
			"E,X,X,O,E,O,E\n" +
			"E,X,X,O,E,O,X\n" +
			"E,X,X,O,E,O,O\n" +
			"E,X,X,O,X,E,E\n" +
			"E,X,X,O,X,E,X\n" +
			"E,X,X,O,X,E,O\n" +
			"E,X,X,O,X,X,E\n" +
			"E,X,X,O,X,X,X\n" +
			"E,X,X,O,X,X,O\n" +
			"E,X,X,O,X,O,E\n" +
			"E,X,X,O,X,O,X\n" +
			"E,X,X,O,X,O,O\n" +
			"E,X,X,O,O,E,E\n" +
			"E,X,X,O,O,E,X\n" +
			"E,X,X,O,O,E,O\n" +
			"E,X,X,O,O,X,E\n" +
			"E,X,X,O,O,X,X\n" +
			"E,X,X,O,O,X,O\n" +
			"E,X,X,O,O,O,E\n" +
			"E,X,X,O,O,O,X\n" +
			"E,X,X,O,O,O,O\n" +
			"E,X,O,E,E,E,E\n" +
			"E,X,O,E,E,E,X\n" +
			"E,X,O,E,E,E,O\n" +
			"E,X,O,E,E,X,E\n" +
			"E,X,O,E,E,X,X\n" +
			"E,X,O,E,E,X,O\n" +
			"E,X,O,E,E,O,E\n" +
			"E,X,O,E,E,O,X\n" +
			"E,X,O,E,E,O,O\n" +
			"E,X,O,E,X,E,E\n" +
			"E,X,O,E,X,E,X\n" +
			"E,X,O,E,X,E,O\n" +
			"E,X,O,E,X,X,E\n" +
			"E,X,O,E,X,X,X\n" +
			"E,X,O,E,X,X,O\n" +
			"E,X,O,E,X,O,E\n" +
			"E,X,O,E,X,O,X\n" +
			"E,X,O,E,X,O,O\n" +
			"E,X,O,E,O,E,E\n" +
			"E,X,O,E,O,E,X\n" +
			"E,X,O,E,O,E,O\n" +
			"E,X,O,E,O,X,E\n" +
			"E,X,O,E,O,X,X\n" +
			"E,X,O,E,O,X,O\n" +
			"E,X,O,E,O,O,E\n" +
			"E,X,O,E,O,O,X\n" +
			"E,X,O,E,O,O,O\n" +
			"E,X,O,X,E,E,E\n" +
			"E,X,O,X,E,E,X\n" +
			"E,X,O,X,E,E,O\n" +
			"E,X,O,X,E,X,E\n" +
			"E,X,O,X,E,X,X\n" +
			"E,X,O,X,E,X,O\n" +
			"E,X,O,X,E,O,E\n" +
			"E,X,O,X,E,O,X\n" +
			"E,X,O,X,E,O,O\n" +
			"E,X,O,X,X,E,E\n" +
			"E,X,O,X,X,E,X\n" +
			"E,X,O,X,X,E,O\n" +
			"E,X,O,X,X,X,E\n" +
			"E,X,O,X,X,X,X\n" +
			"E,X,O,X,X,X,O\n" +
			"E,X,O,X,X,O,E\n" +
			"E,X,O,X,X,O,X\n" +
			"E,X,O,X,X,O,O\n" +
			"E,X,O,X,O,E,E\n" +
			"E,X,O,X,O,E,X\n" +
			"E,X,O,X,O,E,O\n" +
			"E,X,O,X,O,X,E\n" +
			"E,X,O,X,O,X,X\n" +
			"E,X,O,X,O,X,O\n" +
			"E,X,O,X,O,O,E\n" +
			"E,X,O,X,O,O,X\n" +
			"E,X,O,X,O,O,O\n" +
			"E,X,O,O,E,E,E\n" +
			"E,X,O,O,E,E,X\n" +
			"E,X,O,O,E,E,O\n" +
			"E,X,O,O,E,X,E\n" +
			"E,X,O,O,E,X,X\n" +
			"E,X,O,O,E,X,O\n" +
			"E,X,O,O,E,O,E\n" +
			"E,X,O,O,E,O,X\n" +
			"E,X,O,O,E,O,O\n" +
			"E,X,O,O,X,E,E\n" +
			"E,X,O,O,X,E,X\n" +
			"E,X,O,O,X,E,O\n" +
			"E,X,O,O,X,X,E\n" +
			"E,X,O,O,X,X,X\n" +
			"E,X,O,O,X,X,O\n" +
			"E,X,O,O,X,O,E\n" +
			"E,X,O,O,X,O,X\n" +
			"E,X,O,O,X,O,O\n" +
			"E,X,O,O,O,E,E\n" +
			"E,X,O,O,O,E,X\n" +
			"E,X,O,O,O,E,O\n" +
			"E,X,O,O,O,X,E\n" +
			"E,X,O,O,O,X,X\n" +
			"E,X,O,O,O,X,O\n" +
			"E,X,O,O,O,O,E\n" +
			"E,X,O,O,O,O,X\n" +
			"E,X,O,O,O,O,O\n" +
			"E,O,E,E,E,E,E\n" +
			"E,O,E,E,E,E,X\n" +
			"E,O,E,E,E,E,O\n" +
			"E,O,E,E,E,X,E\n" +
			"E,O,E,E,E,X,X\n" +
			"E,O,E,E,E,X,O\n" +
			"E,O,E,E,E,O,E\n" +
			"E,O,E,E,E,O,X\n" +
			"E,O,E,E,E,O,O\n" +
			"E,O,E,E,X,E,E\n" +
			"E,O,E,E,X,E,X\n" +
			"E,O,E,E,X,E,O\n" +
			"E,O,E,E,X,X,E\n" +
			"E,O,E,E,X,X,X\n" +
			"E,O,E,E,X,X,O\n" +
			"E,O,E,E,X,O,E\n" +
			"E,O,E,E,X,O,X\n" +
			"E,O,E,E,X,O,O\n" +
			"E,O,E,E,O,E,E\n" +
			"E,O,E,E,O,E,X\n" +
			"E,O,E,E,O,E,O\n" +
			"E,O,E,E,O,X,E\n" +
			"E,O,E,E,O,X,X\n" +
			"E,O,E,E,O,X,O\n" +
			"E,O,E,E,O,O,E\n" +
			"E,O,E,E,O,O,X\n" +
			"E,O,E,E,O,O,O\n" +
			"E,O,E,X,E,E,E\n" +
			"E,O,E,X,E,E,X\n" +
			"E,O,E,X,E,E,O\n" +
			"E,O,E,X,E,X,E\n" +
			"E,O,E,X,E,X,X\n" +
			"E,O,E,X,E,X,O\n" +
			"E,O,E,X,E,O,E\n" +
			"E,O,E,X,E,O,X\n" +
			"E,O,E,X,E,O,O\n" +
			"E,O,E,X,X,E,E\n" +
			"E,O,E,X,X,E,X\n" +
			"E,O,E,X,X,E,O\n" +
			"E,O,E,X,X,X,E\n" +
			"E,O,E,X,X,X,X\n" +
			"E,O,E,X,X,X,O\n" +
			"E,O,E,X,X,O,E\n" +
			"E,O,E,X,X,O,X\n" +
			"E,O,E,X,X,O,O\n" +
			"E,O,E,X,O,E,E\n" +
			"E,O,E,X,O,E,X\n" +
			"E,O,E,X,O,E,O\n" +
			"E,O,E,X,O,X,E\n" +
			"E,O,E,X,O,X,X\n" +
			"E,O,E,X,O,X,O\n" +
			"E,O,E,X,O,O,E\n" +
			"E,O,E,X,O,O,X\n" +
			"E,O,E,X,O,O,O\n" +
			"E,O,E,O,E,E,E\n" +
			"E,O,E,O,E,E,X\n" +
			"E,O,E,O,E,E,O\n" +
			"E,O,E,O,E,X,E\n" +
			"E,O,E,O,E,X,X\n" +
			"E,O,E,O,E,X,O\n" +
			"E,O,E,O,E,O,E\n" +
			"E,O,E,O,E,O,X\n" +
			"E,O,E,O,E,O,O\n" +
			"E,O,E,O,X,E,E\n" +
			"E,O,E,O,X,E,X\n" +
			"E,O,E,O,X,E,O\n" +
			"E,O,E,O,X,X,E\n" +
			"E,O,E,O,X,X,X\n" +
			"E,O,E,O,X,X,O\n" +
			"E,O,E,O,X,O,E\n" +
			"E,O,E,O,X,O,X\n" +
			"E,O,E,O,X,O,O\n" +
			"E,O,E,O,O,E,E\n" +
			"E,O,E,O,O,E,X\n" +
			"E,O,E,O,O,E,O\n" +
			"E,O,E,O,O,X,E\n" +
			"E,O,E,O,O,X,X\n" +
			"E,O,E,O,O,X,O\n" +
			"E,O,E,O,O,O,E\n" +
			"E,O,E,O,O,O,X\n" +
			"E,O,E,O,O,O,O\n" +
			"E,O,X,E,E,E,E\n" +
			"E,O,X,E,E,E,X\n" +
			"E,O,X,E,E,E,O\n" +
			"E,O,X,E,E,X,E\n" +
			"E,O,X,E,E,X,X\n" +
			"E,O,X,E,E,X,O\n" +
			"E,O,X,E,E,O,E\n" +
			"E,O,X,E,E,O,X\n" +
			"E,O,X,E,E,O,O\n" +
			"E,O,X,E,X,E,E\n" +
			"E,O,X,E,X,E,X\n" +
			"E,O,X,E,X,E,O\n" +
			"E,O,X,E,X,X,E\n" +
			"E,O,X,E,X,X,X\n" +
			"E,O,X,E,X,X,O\n" +
			"E,O,X,E,X,O,E\n" +
			"E,O,X,E,X,O,X\n" +
			"E,O,X,E,X,O,O\n" +
			"E,O,X,E,O,E,E\n" +
			"E,O,X,E,O,E,X\n" +
			"E,O,X,E,O,E,O\n" +
			"E,O,X,E,O,X,E\n" +
			"E,O,X,E,O,X,X\n" +
			"E,O,X,E,O,X,O\n" +
			"E,O,X,E,O,O,E\n" +
			"E,O,X,E,O,O,X\n" +
			"E,O,X,E,O,O,O\n" +
			"E,O,X,X,E,E,E\n" +
			"E,O,X,X,E,E,X\n" +
			"E,O,X,X,E,E,O\n" +
			"E,O,X,X,E,X,E\n" +
			"E,O,X,X,E,X,X\n" +
			"E,O,X,X,E,X,O\n" +
			"E,O,X,X,E,O,E\n" +
			"E,O,X,X,E,O,X\n" +
			"E,O,X,X,E,O,O\n" +
			"E,O,X,X,X,E,E\n" +
			"E,O,X,X,X,E,X\n" +
			"E,O,X,X,X,E,O\n" +
			"E,O,X,X,X,X,E\n" +
			"E,O,X,X,X,X,X\n" +
			"E,O,X,X,X,X,O\n" +
			"E,O,X,X,X,O,E\n" +
			"E,O,X,X,X,O,X\n" +
			"E,O,X,X,X,O,O\n" +
			"E,O,X,X,O,E,E\n" +
			"E,O,X,X,O,E,X\n" +
			"E,O,X,X,O,E,O\n" +
			"E,O,X,X,O,X,E\n" +
			"E,O,X,X,O,X,X\n" +
			"E,O,X,X,O,X,O\n" +
			"E,O,X,X,O,O,E\n" +
			"E,O,X,X,O,O,X\n" +
			"E,O,X,X,O,O,O\n" +
			"E,O,X,O,E,E,E\n" +
			"E,O,X,O,E,E,X\n" +
			"E,O,X,O,E,E,O\n" +
			"E,O,X,O,E,X,E\n" +
			"E,O,X,O,E,X,X\n" +
			"E,O,X,O,E,X,O\n" +
			"E,O,X,O,E,O,E\n" +
			"E,O,X,O,E,O,X\n" +
			"E,O,X,O,E,O,O\n" +
			"E,O,X,O,X,E,E\n" +
			"E,O,X,O,X,E,X\n" +
			"E,O,X,O,X,E,O\n" +
			"E,O,X,O,X,X,E\n" +
			"E,O,X,O,X,X,X\n" +
			"E,O,X,O,X,X,O\n" +
			"E,O,X,O,X,O,E\n" +
			"E,O,X,O,X,O,X\n" +
			"E,O,X,O,X,O,O\n" +
			"E,O,X,O,O,E,E\n" +
			"E,O,X,O,O,E,X\n" +
			"E,O,X,O,O,E,O\n" +
			"E,O,X,O,O,X,E\n" +
			"E,O,X,O,O,X,X\n" +
			"E,O,X,O,O,X,O\n" +
			"E,O,X,O,O,O,E\n" +
			"E,O,X,O,O,O,X\n" +
			"E,O,X,O,O,O,O\n" +
			"E,O,O,E,E,E,E\n" +
			"E,O,O,E,E,E,X\n" +
			"E,O,O,E,E,E,O\n" +
			"E,O,O,E,E,X,E\n" +
			"E,O,O,E,E,X,X\n" +
			"E,O,O,E,E,X,O\n" +
			"E,O,O,E,E,O,E\n" +
			"E,O,O,E,E,O,X\n" +
			"E,O,O,E,E,O,O\n" +
			"E,O,O,E,X,E,E\n" +
			"E,O,O,E,X,E,X\n" +
			"E,O,O,E,X,E,O\n" +
			"E,O,O,E,X,X,E\n" +
			"E,O,O,E,X,X,X\n" +
			"E,O,O,E,X,X,O\n" +
			"E,O,O,E,X,O,E\n" +
			"E,O,O,E,X,O,X\n" +
			"E,O,O,E,X,O,O\n" +
			"E,O,O,E,O,E,E\n" +
			"E,O,O,E,O,E,X\n" +
			"E,O,O,E,O,E,O\n" +
			"E,O,O,E,O,X,E\n" +
			"E,O,O,E,O,X,X\n" +
			"E,O,O,E,O,X,O\n" +
			"E,O,O,E,O,O,E\n" +
			"E,O,O,E,O,O,X\n" +
			"E,O,O,E,O,O,O\n" +
			"E,O,O,X,E,E,E\n" +
			"E,O,O,X,E,E,X\n" +
			"E,O,O,X,E,E,O\n" +
			"E,O,O,X,E,X,E\n" +
			"E,O,O,X,E,X,X\n" +
			"E,O,O,X,E,X,O\n" +
			"E,O,O,X,E,O,E\n" +
			"E,O,O,X,E,O,X\n" +
			"E,O,O,X,E,O,O\n" +
			"E,O,O,X,X,E,E\n" +
			"E,O,O,X,X,E,X\n" +
			"E,O,O,X,X,E,O\n" +
			"E,O,O,X,X,X,E\n" +
			"E,O,O,X,X,X,X\n" +
			"E,O,O,X,X,X,O\n" +
			"E,O,O,X,X,O,E\n" +
			"E,O,O,X,X,O,X\n" +
			"E,O,O,X,X,O,O\n" +
			"E,O,O,X,O,E,E\n" +
			"E,O,O,X,O,E,X\n" +
			"E,O,O,X,O,E,O\n" +
			"E,O,O,X,O,X,E\n" +
			"E,O,O,X,O,X,X\n" +
			"E,O,O,X,O,X,O\n" +
			"E,O,O,X,O,O,E\n" +
			"E,O,O,X,O,O,X\n" +
			"E,O,O,X,O,O,O\n" +
			"E,O,O,O,E,E,E\n" +
			"E,O,O,O,E,E,X\n" +
			"E,O,O,O,E,E,O\n" +
			"E,O,O,O,E,X,E\n" +
			"E,O,O,O,E,X,X\n" +
			"E,O,O,O,E,X,O\n" +
			"E,O,O,O,E,O,E\n" +
			"E,O,O,O,E,O,X\n" +
			"E,O,O,O,E,O,O\n" +
			"E,O,O,O,X,E,E\n" +
			"E,O,O,O,X,E,X\n" +
			"E,O,O,O,X,E,O\n" +
			"E,O,O,O,X,X,E\n" +
			"E,O,O,O,X,X,X\n" +
			"E,O,O,O,X,X,O\n" +
			"E,O,O,O,X,O,E\n" +
			"E,O,O,O,X,O,X\n" +
			"E,O,O,O,X,O,O\n" +
			"E,O,O,O,O,E,E\n" +
			"E,O,O,O,O,E,X\n" +
			"E,O,O,O,O,E,O\n" +
			"E,O,O,O,O,X,E\n" +
			"E,O,O,O,O,X,X\n" +
			"E,O,O,O,O,X,O\n" +
			"E,O,O,O,O,O,E\n" +
			"E,O,O,O,O,O,X\n" +
			"E,O,O,O,O,O,O\n" +
			"X,E,E,E,E,E,E\n" +
			"X,E,E,E,E,E,X\n" +
			"X,E,E,E,E,E,O\n" +
			"X,E,E,E,E,X,E\n" +
			"X,E,E,E,E,X,X\n" +
			"X,E,E,E,E,X,O\n" +
			"X,E,E,E,E,O,E\n" +
			"X,E,E,E,E,O,X\n" +
			"X,E,E,E,E,O,O\n" +
			"X,E,E,E,X,E,E\n" +
			"X,E,E,E,X,E,X\n" +
			"X,E,E,E,X,E,O\n" +
			"X,E,E,E,X,X,E\n" +
			"X,E,E,E,X,X,X\n" +
			"X,E,E,E,X,X,O\n" +
			"X,E,E,E,X,O,E\n" +
			"X,E,E,E,X,O,X\n" +
			"X,E,E,E,X,O,O\n" +
			"X,E,E,E,O,E,E\n" +
			"X,E,E,E,O,E,X\n" +
			"X,E,E,E,O,E,O\n" +
			"X,E,E,E,O,X,E\n" +
			"X,E,E,E,O,X,X\n" +
			"X,E,E,E,O,X,O\n" +
			"X,E,E,E,O,O,E\n" +
			"X,E,E,E,O,O,X\n" +
			"X,E,E,E,O,O,O\n" +
			"X,E,E,X,E,E,E\n" +
			"X,E,E,X,E,E,X\n" +
			"X,E,E,X,E,E,O\n" +
			"X,E,E,X,E,X,E\n" +
			"X,E,E,X,E,X,X\n" +
			"X,E,E,X,E,X,O\n" +
			"X,E,E,X,E,O,E\n" +
			"X,E,E,X,E,O,X\n" +
			"X,E,E,X,E,O,O\n" +
			"X,E,E,X,X,E,E\n" +
			"X,E,E,X,X,E,X\n" +
			"X,E,E,X,X,E,O\n" +
			"X,E,E,X,X,X,E\n" +
			"X,E,E,X,X,X,X\n" +
			"X,E,E,X,X,X,O\n" +
			"X,E,E,X,X,O,E\n" +
			"X,E,E,X,X,O,X\n" +
			"X,E,E,X,X,O,O\n" +
			"X,E,E,X,O,E,E\n" +
			"X,E,E,X,O,E,X\n" +
			"X,E,E,X,O,E,O\n" +
			"X,E,E,X,O,X,E\n" +
			"X,E,E,X,O,X,X\n" +
			"X,E,E,X,O,X,O\n" +
			"X,E,E,X,O,O,E\n" +
			"X,E,E,X,O,O,X\n" +
			"X,E,E,X,O,O,O\n" +
			"X,E,E,O,E,E,E\n" +
			"X,E,E,O,E,E,X\n" +
			"X,E,E,O,E,E,O\n" +
			"X,E,E,O,E,X,E\n" +
			"X,E,E,O,E,X,X\n" +
			"X,E,E,O,E,X,O\n" +
			"X,E,E,O,E,O,E\n" +
			"X,E,E,O,E,O,X\n" +
			"X,E,E,O,E,O,O\n" +
			"X,E,E,O,X,E,E\n" +
			"X,E,E,O,X,E,X\n" +
			"X,E,E,O,X,E,O\n" +
			"X,E,E,O,X,X,E\n" +
			"X,E,E,O,X,X,X\n" +
			"X,E,E,O,X,X,O\n" +
			"X,E,E,O,X,O,E\n" +
			"X,E,E,O,X,O,X\n" +
			"X,E,E,O,X,O,O\n" +
			"X,E,E,O,O,E,E\n" +
			"X,E,E,O,O,E,X\n" +
			"X,E,E,O,O,E,O\n" +
			"X,E,E,O,O,X,E\n" +
			"X,E,E,O,O,X,X\n" +
			"X,E,E,O,O,X,O\n" +
			"X,E,E,O,O,O,E\n" +
			"X,E,E,O,O,O,X\n" +
			"X,E,E,O,O,O,O\n" +
			"X,E,X,E,E,E,E\n" +
			"X,E,X,E,E,E,X\n" +
			"X,E,X,E,E,E,O\n" +
			"X,E,X,E,E,X,E\n" +
			"X,E,X,E,E,X,X\n" +
			"X,E,X,E,E,X,O\n" +
			"X,E,X,E,E,O,E\n" +
			"X,E,X,E,E,O,X\n" +
			"X,E,X,E,E,O,O\n" +
			"X,E,X,E,X,E,E\n" +
			"X,E,X,E,X,E,X\n" +
			"X,E,X,E,X,E,O\n" +
			"X,E,X,E,X,X,E\n" +
			"X,E,X,E,X,X,X\n" +
			"X,E,X,E,X,X,O\n" +
			"X,E,X,E,X,O,E\n" +
			"X,E,X,E,X,O,X\n" +
			"X,E,X,E,X,O,O\n" +
			"X,E,X,E,O,E,E\n" +
			"X,E,X,E,O,E,X\n" +
			"X,E,X,E,O,E,O\n" +
			"X,E,X,E,O,X,E\n" +
			"X,E,X,E,O,X,X\n" +
			"X,E,X,E,O,X,O\n" +
			"X,E,X,E,O,O,E\n" +
			"X,E,X,E,O,O,X\n" +
			"X,E,X,E,O,O,O\n" +
			"X,E,X,X,E,E,E\n" +
			"X,E,X,X,E,E,X\n" +
			"X,E,X,X,E,E,O\n" +
			"X,E,X,X,E,X,E\n" +
			"X,E,X,X,E,X,X\n" +
			"X,E,X,X,E,X,O\n" +
			"X,E,X,X,E,O,E\n" +
			"X,E,X,X,E,O,X\n" +
			"X,E,X,X,E,O,O\n" +
			"X,E,X,X,X,E,E\n" +
			"X,E,X,X,X,E,X\n" +
			"X,E,X,X,X,E,O\n" +
			"X,E,X,X,X,X,E\n" +
			"X,E,X,X,X,X,X\n" +
			"X,E,X,X,X,X,O\n" +
			"X,E,X,X,X,O,E\n" +
			"X,E,X,X,X,O,X\n" +
			"X,E,X,X,X,O,O\n" +
			"X,E,X,X,O,E,E\n" +
			"X,E,X,X,O,E,X\n" +
			"X,E,X,X,O,E,O\n" +
			"X,E,X,X,O,X,E\n" +
			"X,E,X,X,O,X,X\n" +
			"X,E,X,X,O,X,O\n" +
			"X,E,X,X,O,O,E\n" +
			"X,E,X,X,O,O,X\n" +
			"X,E,X,X,O,O,O\n" +
			"X,E,X,O,E,E,E\n" +
			"X,E,X,O,E,E,X\n" +
			"X,E,X,O,E,E,O\n" +
			"X,E,X,O,E,X,E\n" +
			"X,E,X,O,E,X,X\n" +
			"X,E,X,O,E,X,O\n" +
			"X,E,X,O,E,O,E\n" +
			"X,E,X,O,E,O,X\n" +
			"X,E,X,O,E,O,O\n" +
			"X,E,X,O,X,E,E\n" +
			"X,E,X,O,X,E,X\n" +
			"X,E,X,O,X,E,O\n" +
			"X,E,X,O,X,X,E\n" +
			"X,E,X,O,X,X,X\n" +
			"X,E,X,O,X,X,O\n" +
			"X,E,X,O,X,O,E\n" +
			"X,E,X,O,X,O,X\n" +
			"X,E,X,O,X,O,O\n" +
			"X,E,X,O,O,E,E\n" +
			"X,E,X,O,O,E,X\n" +
			"X,E,X,O,O,E,O\n" +
			"X,E,X,O,O,X,E\n" +
			"X,E,X,O,O,X,X\n" +
			"X,E,X,O,O,X,O\n" +
			"X,E,X,O,O,O,E\n" +
			"X,E,X,O,O,O,X\n" +
			"X,E,X,O,O,O,O\n" +
			"X,E,O,E,E,E,E\n" +
			"X,E,O,E,E,E,X\n" +
			"X,E,O,E,E,E,O\n" +
			"X,E,O,E,E,X,E\n" +
			"X,E,O,E,E,X,X\n" +
			"X,E,O,E,E,X,O\n" +
			"X,E,O,E,E,O,E\n" +
			"X,E,O,E,E,O,X\n" +
			"X,E,O,E,E,O,O\n" +
			"X,E,O,E,X,E,E\n" +
			"X,E,O,E,X,E,X\n" +
			"X,E,O,E,X,E,O\n" +
			"X,E,O,E,X,X,E\n" +
			"X,E,O,E,X,X,X\n" +
			"X,E,O,E,X,X,O\n" +
			"X,E,O,E,X,O,E\n" +
			"X,E,O,E,X,O,X\n" +
			"X,E,O,E,X,O,O\n" +
			"X,E,O,E,O,E,E\n" +
			"X,E,O,E,O,E,X\n" +
			"X,E,O,E,O,E,O\n" +
			"X,E,O,E,O,X,E\n" +
			"X,E,O,E,O,X,X\n" +
			"X,E,O,E,O,X,O\n" +
			"X,E,O,E,O,O,E\n" +
			"X,E,O,E,O,O,X\n" +
			"X,E,O,E,O,O,O\n" +
			"X,E,O,X,E,E,E\n" +
			"X,E,O,X,E,E,X\n" +
			"X,E,O,X,E,E,O\n" +
			"X,E,O,X,E,X,E\n" +
			"X,E,O,X,E,X,X\n" +
			"X,E,O,X,E,X,O\n" +
			"X,E,O,X,E,O,E\n" +
			"X,E,O,X,E,O,X\n" +
			"X,E,O,X,E,O,O\n" +
			"X,E,O,X,X,E,E\n" +
			"X,E,O,X,X,E,X\n" +
			"X,E,O,X,X,E,O\n" +
			"X,E,O,X,X,X,E\n" +
			"X,E,O,X,X,X,X\n" +
			"X,E,O,X,X,X,O\n" +
			"X,E,O,X,X,O,E\n" +
			"X,E,O,X,X,O,X\n" +
			"X,E,O,X,X,O,O\n" +
			"X,E,O,X,O,E,E\n" +
			"X,E,O,X,O,E,X\n" +
			"X,E,O,X,O,E,O\n" +
			"X,E,O,X,O,X,E\n" +
			"X,E,O,X,O,X,X\n" +
			"X,E,O,X,O,X,O\n" +
			"X,E,O,X,O,O,E\n" +
			"X,E,O,X,O,O,X\n" +
			"X,E,O,X,O,O,O\n" +
			"X,E,O,O,E,E,E\n" +
			"X,E,O,O,E,E,X\n" +
			"X,E,O,O,E,E,O\n" +
			"X,E,O,O,E,X,E\n" +
			"X,E,O,O,E,X,X\n" +
			"X,E,O,O,E,X,O\n" +
			"X,E,O,O,E,O,E\n" +
			"X,E,O,O,E,O,X\n" +
			"X,E,O,O,E,O,O\n" +
			"X,E,O,O,X,E,E\n" +
			"X,E,O,O,X,E,X\n" +
			"X,E,O,O,X,E,O\n" +
			"X,E,O,O,X,X,E\n" +
			"X,E,O,O,X,X,X\n" +
			"X,E,O,O,X,X,O\n" +
			"X,E,O,O,X,O,E\n" +
			"X,E,O,O,X,O,X\n" +
			"X,E,O,O,X,O,O\n" +
			"X,E,O,O,O,E,E\n" +
			"X,E,O,O,O,E,X\n" +
			"X,E,O,O,O,E,O\n" +
			"X,E,O,O,O,X,E\n" +
			"X,E,O,O,O,X,X\n" +
			"X,E,O,O,O,X,O\n" +
			"X,E,O,O,O,O,E\n" +
			"X,E,O,O,O,O,X\n" +
			"X,E,O,O,O,O,O\n" +
			"X,X,E,E,E,E,E\n" +
			"X,X,E,E,E,E,X\n" +
			"X,X,E,E,E,E,O\n" +
			"X,X,E,E,E,X,E\n" +
			"X,X,E,E,E,X,X\n" +
			"X,X,E,E,E,X,O\n" +
			"X,X,E,E,E,O,E\n" +
			"X,X,E,E,E,O,X\n" +
			"X,X,E,E,E,O,O\n" +
			"X,X,E,E,X,E,E\n" +
			"X,X,E,E,X,E,X\n" +
			"X,X,E,E,X,E,O\n" +
			"X,X,E,E,X,X,E\n" +
			"X,X,E,E,X,X,X\n" +
			"X,X,E,E,X,X,O\n" +
			"X,X,E,E,X,O,E\n" +
			"X,X,E,E,X,O,X\n" +
			"X,X,E,E,X,O,O\n" +
			"X,X,E,E,O,E,E\n" +
			"X,X,E,E,O,E,X\n" +
			"X,X,E,E,O,E,O\n" +
			"X,X,E,E,O,X,E\n" +
			"X,X,E,E,O,X,X\n" +
			"X,X,E,E,O,X,O\n" +
			"X,X,E,E,O,O,E\n" +
			"X,X,E,E,O,O,X\n" +
			"X,X,E,E,O,O,O\n" +
			"X,X,E,X,E,E,E\n" +
			"X,X,E,X,E,E,X\n" +
			"X,X,E,X,E,E,O\n" +
			"X,X,E,X,E,X,E\n" +
			"X,X,E,X,E,X,X\n" +
			"X,X,E,X,E,X,O\n" +
			"X,X,E,X,E,O,E\n" +
			"X,X,E,X,E,O,X\n" +
			"X,X,E,X,E,O,O\n" +
			"X,X,E,X,X,E,E\n" +
			"X,X,E,X,X,E,X\n" +
			"X,X,E,X,X,E,O\n" +
			"X,X,E,X,X,X,E\n" +
			"X,X,E,X,X,X,X\n" +
			"X,X,E,X,X,X,O\n" +
			"X,X,E,X,X,O,E\n" +
			"X,X,E,X,X,O,X\n" +
			"X,X,E,X,X,O,O\n" +
			"X,X,E,X,O,E,E\n" +
			"X,X,E,X,O,E,X\n" +
			"X,X,E,X,O,E,O\n" +
			"X,X,E,X,O,X,E\n" +
			"X,X,E,X,O,X,X\n" +
			"X,X,E,X,O,X,O\n" +
			"X,X,E,X,O,O,E\n" +
			"X,X,E,X,O,O,X\n" +
			"X,X,E,X,O,O,O\n" +
			"X,X,E,O,E,E,E\n" +
			"X,X,E,O,E,E,X\n" +
			"X,X,E,O,E,E,O\n" +
			"X,X,E,O,E,X,E\n" +
			"X,X,E,O,E,X,X\n" +
			"X,X,E,O,E,X,O\n" +
			"X,X,E,O,E,O,E\n" +
			"X,X,E,O,E,O,X\n" +
			"X,X,E,O,E,O,O\n" +
			"X,X,E,O,X,E,E\n" +
			"X,X,E,O,X,E,X\n" +
			"X,X,E,O,X,E,O\n" +
			"X,X,E,O,X,X,E\n" +
			"X,X,E,O,X,X,X\n" +
			"X,X,E,O,X,X,O\n" +
			"X,X,E,O,X,O,E\n" +
			"X,X,E,O,X,O,X\n" +
			"X,X,E,O,X,O,O\n" +
			"X,X,E,O,O,E,E\n" +
			"X,X,E,O,O,E,X\n" +
			"X,X,E,O,O,E,O\n" +
			"X,X,E,O,O,X,E\n" +
			"X,X,E,O,O,X,X\n" +
			"X,X,E,O,O,X,O\n" +
			"X,X,E,O,O,O,E\n" +
			"X,X,E,O,O,O,X\n" +
			"X,X,E,O,O,O,O\n" +
			"X,X,X,E,E,E,E\n" +
			"X,X,X,E,E,E,X\n" +
			"X,X,X,E,E,E,O\n" +
			"X,X,X,E,E,X,E\n" +
			"X,X,X,E,E,X,X\n" +
			"X,X,X,E,E,X,O\n" +
			"X,X,X,E,E,O,E\n" +
			"X,X,X,E,E,O,X\n" +
			"X,X,X,E,E,O,O\n" +
			"X,X,X,E,X,E,E\n" +
			"X,X,X,E,X,E,X\n" +
			"X,X,X,E,X,E,O\n" +
			"X,X,X,E,X,X,E\n" +
			"X,X,X,E,X,X,X\n" +
			"X,X,X,E,X,X,O\n" +
			"X,X,X,E,X,O,E\n" +
			"X,X,X,E,X,O,X\n" +
			"X,X,X,E,X,O,O\n" +
			"X,X,X,E,O,E,E\n" +
			"X,X,X,E,O,E,X\n" +
			"X,X,X,E,O,E,O\n" +
			"X,X,X,E,O,X,E\n" +
			"X,X,X,E,O,X,X\n" +
			"X,X,X,E,O,X,O\n" +
			"X,X,X,E,O,O,E\n" +
			"X,X,X,E,O,O,X\n" +
			"X,X,X,E,O,O,O\n" +
			"X,X,X,X,E,E,E\n" +
			"X,X,X,X,E,E,X\n" +
			"X,X,X,X,E,E,O\n" +
			"X,X,X,X,E,X,E\n" +
			"X,X,X,X,E,X,X\n" +
			"X,X,X,X,E,X,O\n" +
			"X,X,X,X,E,O,E\n" +
			"X,X,X,X,E,O,X\n" +
			"X,X,X,X,E,O,O\n" +
			"X,X,X,X,X,E,E\n" +
			"X,X,X,X,X,E,X\n" +
			"X,X,X,X,X,E,O\n" +
			"X,X,X,X,X,X,E\n" +
			"X,X,X,X,X,X,X\n" +
			"X,X,X,X,X,X,O\n" +
			"X,X,X,X,X,O,E\n" +
			"X,X,X,X,X,O,X\n" +
			"X,X,X,X,X,O,O\n" +
			"X,X,X,X,O,E,E\n" +
			"X,X,X,X,O,E,X\n" +
			"X,X,X,X,O,E,O\n" +
			"X,X,X,X,O,X,E\n" +
			"X,X,X,X,O,X,X\n" +
			"X,X,X,X,O,X,O\n" +
			"X,X,X,X,O,O,E\n" +
			"X,X,X,X,O,O,X\n" +
			"X,X,X,X,O,O,O\n" +
			"X,X,X,O,E,E,E\n" +
			"X,X,X,O,E,E,X\n" +
			"X,X,X,O,E,E,O\n" +
			"X,X,X,O,E,X,E\n" +
			"X,X,X,O,E,X,X\n" +
			"X,X,X,O,E,X,O\n" +
			"X,X,X,O,E,O,E\n" +
			"X,X,X,O,E,O,X\n" +
			"X,X,X,O,E,O,O\n" +
			"X,X,X,O,X,E,E\n" +
			"X,X,X,O,X,E,X\n" +
			"X,X,X,O,X,E,O\n" +
			"X,X,X,O,X,X,E\n" +
			"X,X,X,O,X,X,X\n" +
			"X,X,X,O,X,X,O\n" +
			"X,X,X,O,X,O,E\n" +
			"X,X,X,O,X,O,X\n" +
			"X,X,X,O,X,O,O\n" +
			"X,X,X,O,O,E,E\n" +
			"X,X,X,O,O,E,X\n" +
			"X,X,X,O,O,E,O\n" +
			"X,X,X,O,O,X,E\n" +
			"X,X,X,O,O,X,X\n" +
			"X,X,X,O,O,X,O\n" +
			"X,X,X,O,O,O,E\n" +
			"X,X,X,O,O,O,X\n" +
			"X,X,X,O,O,O,O\n" +
			"X,X,O,E,E,E,E\n" +
			"X,X,O,E,E,E,X\n" +
			"X,X,O,E,E,E,O\n" +
			"X,X,O,E,E,X,E\n" +
			"X,X,O,E,E,X,X\n" +
			"X,X,O,E,E,X,O\n" +
			"X,X,O,E,E,O,E\n" +
			"X,X,O,E,E,O,X\n" +
			"X,X,O,E,E,O,O\n" +
			"X,X,O,E,X,E,E\n" +
			"X,X,O,E,X,E,X\n" +
			"X,X,O,E,X,E,O\n" +
			"X,X,O,E,X,X,E\n" +
			"X,X,O,E,X,X,X\n" +
			"X,X,O,E,X,X,O\n" +
			"X,X,O,E,X,O,E\n" +
			"X,X,O,E,X,O,X\n" +
			"X,X,O,E,X,O,O\n" +
			"X,X,O,E,O,E,E\n" +
			"X,X,O,E,O,E,X\n" +
			"X,X,O,E,O,E,O\n" +
			"X,X,O,E,O,X,E\n" +
			"X,X,O,E,O,X,X\n" +
			"X,X,O,E,O,X,O\n" +
			"X,X,O,E,O,O,E\n" +
			"X,X,O,E,O,O,X\n" +
			"X,X,O,E,O,O,O\n" +
			"X,X,O,X,E,E,E\n" +
			"X,X,O,X,E,E,X\n" +
			"X,X,O,X,E,E,O\n" +
			"X,X,O,X,E,X,E\n" +
			"X,X,O,X,E,X,X\n" +
			"X,X,O,X,E,X,O\n" +
			"X,X,O,X,E,O,E\n" +
			"X,X,O,X,E,O,X\n" +
			"X,X,O,X,E,O,O\n" +
			"X,X,O,X,X,E,E\n" +
			"X,X,O,X,X,E,X\n" +
			"X,X,O,X,X,E,O\n" +
			"X,X,O,X,X,X,E\n" +
			"X,X,O,X,X,X,X\n" +
			"X,X,O,X,X,X,O\n" +
			"X,X,O,X,X,O,E\n" +
			"X,X,O,X,X,O,X\n" +
			"X,X,O,X,X,O,O\n" +
			"X,X,O,X,O,E,E\n" +
			"X,X,O,X,O,E,X\n" +
			"X,X,O,X,O,E,O\n" +
			"X,X,O,X,O,X,E\n" +
			"X,X,O,X,O,X,X\n" +
			"X,X,O,X,O,X,O\n" +
			"X,X,O,X,O,O,E\n" +
			"X,X,O,X,O,O,X\n" +
			"X,X,O,X,O,O,O\n" +
			"X,X,O,O,E,E,E\n" +
			"X,X,O,O,E,E,X\n" +
			"X,X,O,O,E,E,O\n" +
			"X,X,O,O,E,X,E\n" +
			"X,X,O,O,E,X,X\n" +
			"X,X,O,O,E,X,O\n" +
			"X,X,O,O,E,O,E\n" +
			"X,X,O,O,E,O,X\n" +
			"X,X,O,O,E,O,O\n" +
			"X,X,O,O,X,E,E\n" +
			"X,X,O,O,X,E,X\n" +
			"X,X,O,O,X,E,O\n" +
			"X,X,O,O,X,X,E\n" +
			"X,X,O,O,X,X,X\n" +
			"X,X,O,O,X,X,O\n" +
			"X,X,O,O,X,O,E\n" +
			"X,X,O,O,X,O,X\n" +
			"X,X,O,O,X,O,O\n" +
			"X,X,O,O,O,E,E\n" +
			"X,X,O,O,O,E,X\n" +
			"X,X,O,O,O,E,O\n" +
			"X,X,O,O,O,X,E\n" +
			"X,X,O,O,O,X,X\n" +
			"X,X,O,O,O,X,O\n" +
			"X,X,O,O,O,O,E\n" +
			"X,X,O,O,O,O,X\n" +
			"X,X,O,O,O,O,O\n" +
			"X,O,E,E,E,E,E\n" +
			"X,O,E,E,E,E,X\n" +
			"X,O,E,E,E,E,O\n" +
			"X,O,E,E,E,X,E\n" +
			"X,O,E,E,E,X,X\n" +
			"X,O,E,E,E,X,O\n" +
			"X,O,E,E,E,O,E\n" +
			"X,O,E,E,E,O,X\n" +
			"X,O,E,E,E,O,O\n" +
			"X,O,E,E,X,E,E\n" +
			"X,O,E,E,X,E,X\n" +
			"X,O,E,E,X,E,O\n" +
			"X,O,E,E,X,X,E\n" +
			"X,O,E,E,X,X,X\n" +
			"X,O,E,E,X,X,O\n" +
			"X,O,E,E,X,O,E\n" +
			"X,O,E,E,X,O,X\n" +
			"X,O,E,E,X,O,O\n" +
			"X,O,E,E,O,E,E\n" +
			"X,O,E,E,O,E,X\n" +
			"X,O,E,E,O,E,O\n" +
			"X,O,E,E,O,X,E\n" +
			"X,O,E,E,O,X,X\n" +
			"X,O,E,E,O,X,O\n" +
			"X,O,E,E,O,O,E\n" +
			"X,O,E,E,O,O,X\n" +
			"X,O,E,E,O,O,O\n" +
			"X,O,E,X,E,E,E\n" +
			"X,O,E,X,E,E,X\n" +
			"X,O,E,X,E,E,O\n" +
			"X,O,E,X,E,X,E\n" +
			"X,O,E,X,E,X,X\n" +
			"X,O,E,X,E,X,O\n" +
			"X,O,E,X,E,O,E\n" +
			"X,O,E,X,E,O,X\n" +
			"X,O,E,X,E,O,O\n" +
			"X,O,E,X,X,E,E\n" +
			"X,O,E,X,X,E,X\n" +
			"X,O,E,X,X,E,O\n" +
			"X,O,E,X,X,X,E\n" +
			"X,O,E,X,X,X,X\n" +
			"X,O,E,X,X,X,O\n" +
			"X,O,E,X,X,O,E\n" +
			"X,O,E,X,X,O,X\n" +
			"X,O,E,X,X,O,O\n" +
			"X,O,E,X,O,E,E\n" +
			"X,O,E,X,O,E,X\n" +
			"X,O,E,X,O,E,O\n" +
			"X,O,E,X,O,X,E\n" +
			"X,O,E,X,O,X,X\n" +
			"X,O,E,X,O,X,O\n" +
			"X,O,E,X,O,O,E\n" +
			"X,O,E,X,O,O,X\n" +
			"X,O,E,X,O,O,O\n" +
			"X,O,E,O,E,E,E\n" +
			"X,O,E,O,E,E,X\n" +
			"X,O,E,O,E,E,O\n" +
			"X,O,E,O,E,X,E\n" +
			"X,O,E,O,E,X,X\n" +
			"X,O,E,O,E,X,O\n" +
			"X,O,E,O,E,O,E\n" +
			"X,O,E,O,E,O,X\n" +
			"X,O,E,O,E,O,O\n" +
			"X,O,E,O,X,E,E\n" +
			"X,O,E,O,X,E,X\n" +
			"X,O,E,O,X,E,O\n" +
			"X,O,E,O,X,X,E\n" +
			"X,O,E,O,X,X,X\n" +
			"X,O,E,O,X,X,O\n" +
			"X,O,E,O,X,O,E\n" +
			"X,O,E,O,X,O,X\n" +
			"X,O,E,O,X,O,O\n" +
			"X,O,E,O,O,E,E\n" +
			"X,O,E,O,O,E,X\n" +
			"X,O,E,O,O,E,O\n" +
			"X,O,E,O,O,X,E\n" +
			"X,O,E,O,O,X,X\n" +
			"X,O,E,O,O,X,O\n" +
			"X,O,E,O,O,O,E\n" +
			"X,O,E,O,O,O,X\n" +
			"X,O,E,O,O,O,O\n" +
			"X,O,X,E,E,E,E\n" +
			"X,O,X,E,E,E,X\n" +
			"X,O,X,E,E,E,O\n" +
			"X,O,X,E,E,X,E\n" +
			"X,O,X,E,E,X,X\n" +
			"X,O,X,E,E,X,O\n" +
			"X,O,X,E,E,O,E\n" +
			"X,O,X,E,E,O,X\n" +
			"X,O,X,E,E,O,O\n" +
			"X,O,X,E,X,E,E\n" +
			"X,O,X,E,X,E,X\n" +
			"X,O,X,E,X,E,O\n" +
			"X,O,X,E,X,X,E\n" +
			"X,O,X,E,X,X,X\n" +
			"X,O,X,E,X,X,O\n" +
			"X,O,X,E,X,O,E\n" +
			"X,O,X,E,X,O,X\n" +
			"X,O,X,E,X,O,O\n" +
			"X,O,X,E,O,E,E\n" +
			"X,O,X,E,O,E,X\n" +
			"X,O,X,E,O,E,O\n" +
			"X,O,X,E,O,X,E\n" +
			"X,O,X,E,O,X,X\n" +
			"X,O,X,E,O,X,O\n" +
			"X,O,X,E,O,O,E\n" +
			"X,O,X,E,O,O,X\n" +
			"X,O,X,E,O,O,O\n" +
			"X,O,X,X,E,E,E\n" +
			"X,O,X,X,E,E,X\n" +
			"X,O,X,X,E,E,O\n" +
			"X,O,X,X,E,X,E\n" +
			"X,O,X,X,E,X,X\n" +
			"X,O,X,X,E,X,O\n" +
			"X,O,X,X,E,O,E\n" +
			"X,O,X,X,E,O,X\n" +
			"X,O,X,X,E,O,O\n" +
			"X,O,X,X,X,E,E\n" +
			"X,O,X,X,X,E,X\n" +
			"X,O,X,X,X,E,O\n" +
			"X,O,X,X,X,X,E\n" +
			"X,O,X,X,X,X,X\n" +
			"X,O,X,X,X,X,O\n" +
			"X,O,X,X,X,O,E\n" +
			"X,O,X,X,X,O,X\n" +
			"X,O,X,X,X,O,O\n" +
			"X,O,X,X,O,E,E\n" +
			"X,O,X,X,O,E,X\n" +
			"X,O,X,X,O,E,O\n" +
			"X,O,X,X,O,X,E\n" +
			"X,O,X,X,O,X,X\n" +
			"X,O,X,X,O,X,O\n" +
			"X,O,X,X,O,O,E\n" +
			"X,O,X,X,O,O,X\n" +
			"X,O,X,X,O,O,O\n" +
			"X,O,X,O,E,E,E\n" +
			"X,O,X,O,E,E,X\n" +
			"X,O,X,O,E,E,O\n" +
			"X,O,X,O,E,X,E\n" +
			"X,O,X,O,E,X,X\n" +
			"X,O,X,O,E,X,O\n" +
			"X,O,X,O,E,O,E\n" +
			"X,O,X,O,E,O,X\n" +
			"X,O,X,O,E,O,O\n" +
			"X,O,X,O,X,E,E\n" +
			"X,O,X,O,X,E,X\n" +
			"X,O,X,O,X,E,O\n" +
			"X,O,X,O,X,X,E\n" +
			"X,O,X,O,X,X,X\n" +
			"X,O,X,O,X,X,O\n" +
			"X,O,X,O,X,O,E\n" +
			"X,O,X,O,X,O,X\n" +
			"X,O,X,O,X,O,O\n" +
			"X,O,X,O,O,E,E\n" +
			"X,O,X,O,O,E,X\n" +
			"X,O,X,O,O,E,O\n" +
			"X,O,X,O,O,X,E\n" +
			"X,O,X,O,O,X,X\n" +
			"X,O,X,O,O,X,O\n" +
			"X,O,X,O,O,O,E\n" +
			"X,O,X,O,O,O,X\n" +
			"X,O,X,O,O,O,O\n" +
			"X,O,O,E,E,E,E\n" +
			"X,O,O,E,E,E,X\n" +
			"X,O,O,E,E,E,O\n" +
			"X,O,O,E,E,X,E\n" +
			"X,O,O,E,E,X,X\n" +
			"X,O,O,E,E,X,O\n" +
			"X,O,O,E,E,O,E\n" +
			"X,O,O,E,E,O,X\n" +
			"X,O,O,E,E,O,O\n" +
			"X,O,O,E,X,E,E\n" +
			"X,O,O,E,X,E,X\n" +
			"X,O,O,E,X,E,O\n" +
			"X,O,O,E,X,X,E\n" +
			"X,O,O,E,X,X,X\n" +
			"X,O,O,E,X,X,O\n" +
			"X,O,O,E,X,O,E\n" +
			"X,O,O,E,X,O,X\n" +
			"X,O,O,E,X,O,O\n" +
			"X,O,O,E,O,E,E\n" +
			"X,O,O,E,O,E,X\n" +
			"X,O,O,E,O,E,O\n" +
			"X,O,O,E,O,X,E\n" +
			"X,O,O,E,O,X,X\n" +
			"X,O,O,E,O,X,O\n" +
			"X,O,O,E,O,O,E\n" +
			"X,O,O,E,O,O,X\n" +
			"X,O,O,E,O,O,O\n" +
			"X,O,O,X,E,E,E\n" +
			"X,O,O,X,E,E,X\n" +
			"X,O,O,X,E,E,O\n" +
			"X,O,O,X,E,X,E\n" +
			"X,O,O,X,E,X,X\n" +
			"X,O,O,X,E,X,O\n" +
			"X,O,O,X,E,O,E\n" +
			"X,O,O,X,E,O,X\n" +
			"X,O,O,X,E,O,O\n" +
			"X,O,O,X,X,E,E\n" +
			"X,O,O,X,X,E,X\n" +
			"X,O,O,X,X,E,O\n" +
			"X,O,O,X,X,X,E\n" +
			"X,O,O,X,X,X,X\n" +
			"X,O,O,X,X,X,O\n" +
			"X,O,O,X,X,O,E\n" +
			"X,O,O,X,X,O,X\n" +
			"X,O,O,X,X,O,O\n" +
			"X,O,O,X,O,E,E\n" +
			"X,O,O,X,O,E,X\n" +
			"X,O,O,X,O,E,O\n" +
			"X,O,O,X,O,X,E\n" +
			"X,O,O,X,O,X,X\n" +
			"X,O,O,X,O,X,O\n" +
			"X,O,O,X,O,O,E\n" +
			"X,O,O,X,O,O,X\n" +
			"X,O,O,X,O,O,O\n" +
			"X,O,O,O,E,E,E\n" +
			"X,O,O,O,E,E,X\n" +
			"X,O,O,O,E,E,O\n" +
			"X,O,O,O,E,X,E\n" +
			"X,O,O,O,E,X,X\n" +
			"X,O,O,O,E,X,O\n" +
			"X,O,O,O,E,O,E\n" +
			"X,O,O,O,E,O,X\n" +
			"X,O,O,O,E,O,O\n" +
			"X,O,O,O,X,E,E\n" +
			"X,O,O,O,X,E,X\n" +
			"X,O,O,O,X,E,O\n" +
			"X,O,O,O,X,X,E\n" +
			"X,O,O,O,X,X,X\n" +
			"X,O,O,O,X,X,O\n" +
			"X,O,O,O,X,O,E\n" +
			"X,O,O,O,X,O,X\n" +
			"X,O,O,O,X,O,O\n" +
			"X,O,O,O,O,E,E\n" +
			"X,O,O,O,O,E,X\n" +
			"X,O,O,O,O,E,O\n" +
			"X,O,O,O,O,X,E\n" +
			"X,O,O,O,O,X,X\n" +
			"X,O,O,O,O,X,O\n" +
			"X,O,O,O,O,O,E\n" +
			"X,O,O,O,O,O,X\n" +
			"X,O,O,O,O,O,O\n" +
			"O,E,E,E,E,E,E\n" +
			"O,E,E,E,E,E,X\n" +
			"O,E,E,E,E,E,O\n" +
			"O,E,E,E,E,X,E\n" +
			"O,E,E,E,E,X,X\n" +
			"O,E,E,E,E,X,O\n" +
			"O,E,E,E,E,O,E\n" +
			"O,E,E,E,E,O,X\n" +
			"O,E,E,E,E,O,O\n" +
			"O,E,E,E,X,E,E\n" +
			"O,E,E,E,X,E,X\n" +
			"O,E,E,E,X,E,O\n" +
			"O,E,E,E,X,X,E\n" +
			"O,E,E,E,X,X,X\n" +
			"O,E,E,E,X,X,O\n" +
			"O,E,E,E,X,O,E\n" +
			"O,E,E,E,X,O,X\n" +
			"O,E,E,E,X,O,O\n" +
			"O,E,E,E,O,E,E\n" +
			"O,E,E,E,O,E,X\n" +
			"O,E,E,E,O,E,O\n" +
			"O,E,E,E,O,X,E\n" +
			"O,E,E,E,O,X,X\n" +
			"O,E,E,E,O,X,O\n" +
			"O,E,E,E,O,O,E\n" +
			"O,E,E,E,O,O,X\n" +
			"O,E,E,E,O,O,O\n" +
			"O,E,E,X,E,E,E\n" +
			"O,E,E,X,E,E,X\n" +
			"O,E,E,X,E,E,O\n" +
			"O,E,E,X,E,X,E\n" +
			"O,E,E,X,E,X,X\n" +
			"O,E,E,X,E,X,O\n" +
			"O,E,E,X,E,O,E\n" +
			"O,E,E,X,E,O,X\n" +
			"O,E,E,X,E,O,O\n" +
			"O,E,E,X,X,E,E\n" +
			"O,E,E,X,X,E,X\n" +
			"O,E,E,X,X,E,O\n" +
			"O,E,E,X,X,X,E\n" +
			"O,E,E,X,X,X,X\n" +
			"O,E,E,X,X,X,O\n" +
			"O,E,E,X,X,O,E\n" +
			"O,E,E,X,X,O,X\n" +
			"O,E,E,X,X,O,O\n" +
			"O,E,E,X,O,E,E\n" +
			"O,E,E,X,O,E,X\n" +
			"O,E,E,X,O,E,O\n" +
			"O,E,E,X,O,X,E\n" +
			"O,E,E,X,O,X,X\n" +
			"O,E,E,X,O,X,O\n" +
			"O,E,E,X,O,O,E\n" +
			"O,E,E,X,O,O,X\n" +
			"O,E,E,X,O,O,O\n" +
			"O,E,E,O,E,E,E\n" +
			"O,E,E,O,E,E,X\n" +
			"O,E,E,O,E,E,O\n" +
			"O,E,E,O,E,X,E\n" +
			"O,E,E,O,E,X,X\n" +
			"O,E,E,O,E,X,O\n" +
			"O,E,E,O,E,O,E\n" +
			"O,E,E,O,E,O,X\n" +
			"O,E,E,O,E,O,O\n" +
			"O,E,E,O,X,E,E\n" +
			"O,E,E,O,X,E,X\n" +
			"O,E,E,O,X,E,O\n" +
			"O,E,E,O,X,X,E\n" +
			"O,E,E,O,X,X,X\n" +
			"O,E,E,O,X,X,O\n" +
			"O,E,E,O,X,O,E\n" +
			"O,E,E,O,X,O,X\n" +
			"O,E,E,O,X,O,O\n" +
			"O,E,E,O,O,E,E\n" +
			"O,E,E,O,O,E,X\n" +
			"O,E,E,O,O,E,O\n" +
			"O,E,E,O,O,X,E\n" +
			"O,E,E,O,O,X,X\n" +
			"O,E,E,O,O,X,O\n" +
			"O,E,E,O,O,O,E\n" +
			"O,E,E,O,O,O,X\n" +
			"O,E,E,O,O,O,O\n" +
			"O,E,X,E,E,E,E\n" +
			"O,E,X,E,E,E,X\n" +
			"O,E,X,E,E,E,O\n" +
			"O,E,X,E,E,X,E\n" +
			"O,E,X,E,E,X,X\n" +
			"O,E,X,E,E,X,O\n" +
			"O,E,X,E,E,O,E\n" +
			"O,E,X,E,E,O,X\n" +
			"O,E,X,E,E,O,O\n" +
			"O,E,X,E,X,E,E\n" +
			"O,E,X,E,X,E,X\n" +
			"O,E,X,E,X,E,O\n" +
			"O,E,X,E,X,X,E\n" +
			"O,E,X,E,X,X,X\n" +
			"O,E,X,E,X,X,O\n" +
			"O,E,X,E,X,O,E\n" +
			"O,E,X,E,X,O,X\n" +
			"O,E,X,E,X,O,O\n" +
			"O,E,X,E,O,E,E\n" +
			"O,E,X,E,O,E,X\n" +
			"O,E,X,E,O,E,O\n" +
			"O,E,X,E,O,X,E\n" +
			"O,E,X,E,O,X,X\n" +
			"O,E,X,E,O,X,O\n" +
			"O,E,X,E,O,O,E\n" +
			"O,E,X,E,O,O,X\n" +
			"O,E,X,E,O,O,O\n" +
			"O,E,X,X,E,E,E\n" +
			"O,E,X,X,E,E,X\n" +
			"O,E,X,X,E,E,O\n" +
			"O,E,X,X,E,X,E\n" +
			"O,E,X,X,E,X,X\n" +
			"O,E,X,X,E,X,O\n" +
			"O,E,X,X,E,O,E\n" +
			"O,E,X,X,E,O,X\n" +
			"O,E,X,X,E,O,O\n" +
			"O,E,X,X,X,E,E\n" +
			"O,E,X,X,X,E,X\n" +
			"O,E,X,X,X,E,O\n" +
			"O,E,X,X,X,X,E\n" +
			"O,E,X,X,X,X,X\n" +
			"O,E,X,X,X,X,O\n" +
			"O,E,X,X,X,O,E\n" +
			"O,E,X,X,X,O,X\n" +
			"O,E,X,X,X,O,O\n" +
			"O,E,X,X,O,E,E\n" +
			"O,E,X,X,O,E,X\n" +
			"O,E,X,X,O,E,O\n" +
			"O,E,X,X,O,X,E\n" +
			"O,E,X,X,O,X,X\n" +
			"O,E,X,X,O,X,O\n" +
			"O,E,X,X,O,O,E\n" +
			"O,E,X,X,O,O,X\n" +
			"O,E,X,X,O,O,O\n" +
			"O,E,X,O,E,E,E\n" +
			"O,E,X,O,E,E,X\n" +
			"O,E,X,O,E,E,O\n" +
			"O,E,X,O,E,X,E\n" +
			"O,E,X,O,E,X,X\n" +
			"O,E,X,O,E,X,O\n" +
			"O,E,X,O,E,O,E\n" +
			"O,E,X,O,E,O,X\n" +
			"O,E,X,O,E,O,O\n" +
			"O,E,X,O,X,E,E\n" +
			"O,E,X,O,X,E,X\n" +
			"O,E,X,O,X,E,O\n" +
			"O,E,X,O,X,X,E\n" +
			"O,E,X,O,X,X,X\n" +
			"O,E,X,O,X,X,O\n" +
			"O,E,X,O,X,O,E\n" +
			"O,E,X,O,X,O,X\n" +
			"O,E,X,O,X,O,O\n" +
			"O,E,X,O,O,E,E\n" +
			"O,E,X,O,O,E,X\n" +
			"O,E,X,O,O,E,O\n" +
			"O,E,X,O,O,X,E\n" +
			"O,E,X,O,O,X,X\n" +
			"O,E,X,O,O,X,O\n" +
			"O,E,X,O,O,O,E\n" +
			"O,E,X,O,O,O,X\n" +
			"O,E,X,O,O,O,O\n" +
			"O,E,O,E,E,E,E\n" +
			"O,E,O,E,E,E,X\n" +
			"O,E,O,E,E,E,O\n" +
			"O,E,O,E,E,X,E\n" +
			"O,E,O,E,E,X,X\n" +
			"O,E,O,E,E,X,O\n" +
			"O,E,O,E,E,O,E\n" +
			"O,E,O,E,E,O,X\n" +
			"O,E,O,E,E,O,O\n" +
			"O,E,O,E,X,E,E\n" +
			"O,E,O,E,X,E,X\n" +
			"O,E,O,E,X,E,O\n" +
			"O,E,O,E,X,X,E\n" +
			"O,E,O,E,X,X,X\n" +
			"O,E,O,E,X,X,O\n" +
			"O,E,O,E,X,O,E\n" +
			"O,E,O,E,X,O,X\n" +
			"O,E,O,E,X,O,O\n" +
			"O,E,O,E,O,E,E\n" +
			"O,E,O,E,O,E,X\n" +
			"O,E,O,E,O,E,O\n" +
			"O,E,O,E,O,X,E\n" +
			"O,E,O,E,O,X,X\n" +
			"O,E,O,E,O,X,O\n" +
			"O,E,O,E,O,O,E\n" +
			"O,E,O,E,O,O,X\n" +
			"O,E,O,E,O,O,O\n" +
			"O,E,O,X,E,E,E\n" +
			"O,E,O,X,E,E,X\n" +
			"O,E,O,X,E,E,O\n" +
			"O,E,O,X,E,X,E\n" +
			"O,E,O,X,E,X,X\n" +
			"O,E,O,X,E,X,O\n" +
			"O,E,O,X,E,O,E\n" +
			"O,E,O,X,E,O,X\n" +
			"O,E,O,X,E,O,O\n" +
			"O,E,O,X,X,E,E\n" +
			"O,E,O,X,X,E,X\n" +
			"O,E,O,X,X,E,O\n" +
			"O,E,O,X,X,X,E\n" +
			"O,E,O,X,X,X,X\n" +
			"O,E,O,X,X,X,O\n" +
			"O,E,O,X,X,O,E\n" +
			"O,E,O,X,X,O,X\n" +
			"O,E,O,X,X,O,O\n" +
			"O,E,O,X,O,E,E\n" +
			"O,E,O,X,O,E,X\n" +
			"O,E,O,X,O,E,O\n" +
			"O,E,O,X,O,X,E\n" +
			"O,E,O,X,O,X,X\n" +
			"O,E,O,X,O,X,O\n" +
			"O,E,O,X,O,O,E\n" +
			"O,E,O,X,O,O,X\n" +
			"O,E,O,X,O,O,O\n" +
			"O,E,O,O,E,E,E\n" +
			"O,E,O,O,E,E,X\n" +
			"O,E,O,O,E,E,O\n" +
			"O,E,O,O,E,X,E\n" +
			"O,E,O,O,E,X,X\n" +
			"O,E,O,O,E,X,O\n" +
			"O,E,O,O,E,O,E\n" +
			"O,E,O,O,E,O,X\n" +
			"O,E,O,O,E,O,O\n" +
			"O,E,O,O,X,E,E\n" +
			"O,E,O,O,X,E,X\n" +
			"O,E,O,O,X,E,O\n" +
			"O,E,O,O,X,X,E\n" +
			"O,E,O,O,X,X,X\n" +
			"O,E,O,O,X,X,O\n" +
			"O,E,O,O,X,O,E\n" +
			"O,E,O,O,X,O,X\n" +
			"O,E,O,O,X,O,O\n" +
			"O,E,O,O,O,E,E\n" +
			"O,E,O,O,O,E,X\n" +
			"O,E,O,O,O,E,O\n" +
			"O,E,O,O,O,X,E\n" +
			"O,E,O,O,O,X,X\n" +
			"O,E,O,O,O,X,O\n" +
			"O,E,O,O,O,O,E\n" +
			"O,E,O,O,O,O,X\n" +
			"O,E,O,O,O,O,O\n" +
			"O,X,E,E,E,E,E\n" +
			"O,X,E,E,E,E,X\n" +
			"O,X,E,E,E,E,O\n" +
			"O,X,E,E,E,X,E\n" +
			"O,X,E,E,E,X,X\n" +
			"O,X,E,E,E,X,O\n" +
			"O,X,E,E,E,O,E\n" +
			"O,X,E,E,E,O,X\n" +
			"O,X,E,E,E,O,O\n" +
			"O,X,E,E,X,E,E\n" +
			"O,X,E,E,X,E,X\n" +
			"O,X,E,E,X,E,O\n" +
			"O,X,E,E,X,X,E\n" +
			"O,X,E,E,X,X,X\n" +
			"O,X,E,E,X,X,O\n" +
			"O,X,E,E,X,O,E\n" +
			"O,X,E,E,X,O,X\n" +
			"O,X,E,E,X,O,O\n" +
			"O,X,E,E,O,E,E\n" +
			"O,X,E,E,O,E,X\n" +
			"O,X,E,E,O,E,O\n" +
			"O,X,E,E,O,X,E\n" +
			"O,X,E,E,O,X,X\n" +
			"O,X,E,E,O,X,O\n" +
			"O,X,E,E,O,O,E\n" +
			"O,X,E,E,O,O,X\n" +
			"O,X,E,E,O,O,O\n" +
			"O,X,E,X,E,E,E\n" +
			"O,X,E,X,E,E,X\n" +
			"O,X,E,X,E,E,O\n" +
			"O,X,E,X,E,X,E\n" +
			"O,X,E,X,E,X,X\n" +
			"O,X,E,X,E,X,O\n" +
			"O,X,E,X,E,O,E\n" +
			"O,X,E,X,E,O,X\n" +
			"O,X,E,X,E,O,O\n" +
			"O,X,E,X,X,E,E\n" +
			"O,X,E,X,X,E,X\n" +
			"O,X,E,X,X,E,O\n" +
			"O,X,E,X,X,X,E\n" +
			"O,X,E,X,X,X,X\n" +
			"O,X,E,X,X,X,O\n" +
			"O,X,E,X,X,O,E\n" +
			"O,X,E,X,X,O,X\n" +
			"O,X,E,X,X,O,O\n" +
			"O,X,E,X,O,E,E\n" +
			"O,X,E,X,O,E,X\n" +
			"O,X,E,X,O,E,O\n" +
			"O,X,E,X,O,X,E\n" +
			"O,X,E,X,O,X,X\n" +
			"O,X,E,X,O,X,O\n" +
			"O,X,E,X,O,O,E\n" +
			"O,X,E,X,O,O,X\n" +
			"O,X,E,X,O,O,O\n" +
			"O,X,E,O,E,E,E\n" +
			"O,X,E,O,E,E,X\n" +
			"O,X,E,O,E,E,O\n" +
			"O,X,E,O,E,X,E\n" +
			"O,X,E,O,E,X,X\n" +
			"O,X,E,O,E,X,O\n" +
			"O,X,E,O,E,O,E\n" +
			"O,X,E,O,E,O,X\n" +
			"O,X,E,O,E,O,O\n" +
			"O,X,E,O,X,E,E\n" +
			"O,X,E,O,X,E,X\n" +
			"O,X,E,O,X,E,O\n" +
			"O,X,E,O,X,X,E\n" +
			"O,X,E,O,X,X,X\n" +
			"O,X,E,O,X,X,O\n" +
			"O,X,E,O,X,O,E\n" +
			"O,X,E,O,X,O,X\n" +
			"O,X,E,O,X,O,O\n" +
			"O,X,E,O,O,E,E\n" +
			"O,X,E,O,O,E,X\n" +
			"O,X,E,O,O,E,O\n" +
			"O,X,E,O,O,X,E\n" +
			"O,X,E,O,O,X,X\n" +
			"O,X,E,O,O,X,O\n" +
			"O,X,E,O,O,O,E\n" +
			"O,X,E,O,O,O,X\n" +
			"O,X,E,O,O,O,O\n" +
			"O,X,X,E,E,E,E\n" +
			"O,X,X,E,E,E,X\n" +
			"O,X,X,E,E,E,O\n" +
			"O,X,X,E,E,X,E\n" +
			"O,X,X,E,E,X,X\n" +
			"O,X,X,E,E,X,O\n" +
			"O,X,X,E,E,O,E\n" +
			"O,X,X,E,E,O,X\n" +
			"O,X,X,E,E,O,O\n" +
			"O,X,X,E,X,E,E\n" +
			"O,X,X,E,X,E,X\n" +
			"O,X,X,E,X,E,O\n" +
			"O,X,X,E,X,X,E\n" +
			"O,X,X,E,X,X,X\n" +
			"O,X,X,E,X,X,O\n" +
			"O,X,X,E,X,O,E\n" +
			"O,X,X,E,X,O,X\n" +
			"O,X,X,E,X,O,O\n" +
			"O,X,X,E,O,E,E\n" +
			"O,X,X,E,O,E,X\n" +
			"O,X,X,E,O,E,O\n" +
			"O,X,X,E,O,X,E\n" +
			"O,X,X,E,O,X,X\n" +
			"O,X,X,E,O,X,O\n" +
			"O,X,X,E,O,O,E\n" +
			"O,X,X,E,O,O,X\n" +
			"O,X,X,E,O,O,O\n" +
			"O,X,X,X,E,E,E\n" +
			"O,X,X,X,E,E,X\n" +
			"O,X,X,X,E,E,O\n" +
			"O,X,X,X,E,X,E\n" +
			"O,X,X,X,E,X,X\n" +
			"O,X,X,X,E,X,O\n" +
			"O,X,X,X,E,O,E\n" +
			"O,X,X,X,E,O,X\n" +
			"O,X,X,X,E,O,O\n" +
			"O,X,X,X,X,E,E\n" +
			"O,X,X,X,X,E,X\n" +
			"O,X,X,X,X,E,O\n" +
			"O,X,X,X,X,X,E\n" +
			"O,X,X,X,X,X,X\n" +
			"O,X,X,X,X,X,O\n" +
			"O,X,X,X,X,O,E\n" +
			"O,X,X,X,X,O,X\n" +
			"O,X,X,X,X,O,O\n" +
			"O,X,X,X,O,E,E\n" +
			"O,X,X,X,O,E,X\n" +
			"O,X,X,X,O,E,O\n" +
			"O,X,X,X,O,X,E\n" +
			"O,X,X,X,O,X,X\n" +
			"O,X,X,X,O,X,O\n" +
			"O,X,X,X,O,O,E\n" +
			"O,X,X,X,O,O,X\n" +
			"O,X,X,X,O,O,O\n" +
			"O,X,X,O,E,E,E\n" +
			"O,X,X,O,E,E,X\n" +
			"O,X,X,O,E,E,O\n" +
			"O,X,X,O,E,X,E\n" +
			"O,X,X,O,E,X,X\n" +
			"O,X,X,O,E,X,O\n" +
			"O,X,X,O,E,O,E\n" +
			"O,X,X,O,E,O,X\n" +
			"O,X,X,O,E,O,O\n" +
			"O,X,X,O,X,E,E\n" +
			"O,X,X,O,X,E,X\n" +
			"O,X,X,O,X,E,O\n" +
			"O,X,X,O,X,X,E\n" +
			"O,X,X,O,X,X,X\n" +
			"O,X,X,O,X,X,O\n" +
			"O,X,X,O,X,O,E\n" +
			"O,X,X,O,X,O,X\n" +
			"O,X,X,O,X,O,O\n" +
			"O,X,X,O,O,E,E\n" +
			"O,X,X,O,O,E,X\n" +
			"O,X,X,O,O,E,O\n" +
			"O,X,X,O,O,X,E\n" +
			"O,X,X,O,O,X,X\n" +
			"O,X,X,O,O,X,O\n" +
			"O,X,X,O,O,O,E\n" +
			"O,X,X,O,O,O,X\n" +
			"O,X,X,O,O,O,O\n" +
			"O,X,O,E,E,E,E\n" +
			"O,X,O,E,E,E,X\n" +
			"O,X,O,E,E,E,O\n" +
			"O,X,O,E,E,X,E\n" +
			"O,X,O,E,E,X,X\n" +
			"O,X,O,E,E,X,O\n" +
			"O,X,O,E,E,O,E\n" +
			"O,X,O,E,E,O,X\n" +
			"O,X,O,E,E,O,O\n" +
			"O,X,O,E,X,E,E\n" +
			"O,X,O,E,X,E,X\n" +
			"O,X,O,E,X,E,O\n" +
			"O,X,O,E,X,X,E\n" +
			"O,X,O,E,X,X,X\n" +
			"O,X,O,E,X,X,O\n" +
			"O,X,O,E,X,O,E\n" +
			"O,X,O,E,X,O,X\n" +
			"O,X,O,E,X,O,O\n" +
			"O,X,O,E,O,E,E\n" +
			"O,X,O,E,O,E,X\n" +
			"O,X,O,E,O,E,O\n" +
			"O,X,O,E,O,X,E\n" +
			"O,X,O,E,O,X,X\n" +
			"O,X,O,E,O,X,O\n" +
			"O,X,O,E,O,O,E\n" +
			"O,X,O,E,O,O,X\n" +
			"O,X,O,E,O,O,O\n" +
			"O,X,O,X,E,E,E\n" +
			"O,X,O,X,E,E,X\n" +
			"O,X,O,X,E,E,O\n" +
			"O,X,O,X,E,X,E\n" +
			"O,X,O,X,E,X,X\n" +
			"O,X,O,X,E,X,O\n" +
			"O,X,O,X,E,O,E\n" +
			"O,X,O,X,E,O,X\n" +
			"O,X,O,X,E,O,O\n" +
			"O,X,O,X,X,E,E\n" +
			"O,X,O,X,X,E,X\n" +
			"O,X,O,X,X,E,O\n" +
			"O,X,O,X,X,X,E\n" +
			"O,X,O,X,X,X,X\n" +
			"O,X,O,X,X,X,O\n" +
			"O,X,O,X,X,O,E\n" +
			"O,X,O,X,X,O,X\n" +
			"O,X,O,X,X,O,O\n" +
			"O,X,O,X,O,E,E\n" +
			"O,X,O,X,O,E,X\n" +
			"O,X,O,X,O,E,O\n" +
			"O,X,O,X,O,X,E\n" +
			"O,X,O,X,O,X,X\n" +
			"O,X,O,X,O,X,O\n" +
			"O,X,O,X,O,O,E\n" +
			"O,X,O,X,O,O,X\n" +
			"O,X,O,X,O,O,O\n" +
			"O,X,O,O,E,E,E\n" +
			"O,X,O,O,E,E,X\n" +
			"O,X,O,O,E,E,O\n" +
			"O,X,O,O,E,X,E\n" +
			"O,X,O,O,E,X,X\n" +
			"O,X,O,O,E,X,O\n" +
			"O,X,O,O,E,O,E\n" +
			"O,X,O,O,E,O,X\n" +
			"O,X,O,O,E,O,O\n" +
			"O,X,O,O,X,E,E\n" +
			"O,X,O,O,X,E,X\n" +
			"O,X,O,O,X,E,O\n" +
			"O,X,O,O,X,X,E\n" +
			"O,X,O,O,X,X,X\n" +
			"O,X,O,O,X,X,O\n" +
			"O,X,O,O,X,O,E\n" +
			"O,X,O,O,X,O,X\n" +
			"O,X,O,O,X,O,O\n" +
			"O,X,O,O,O,E,E\n" +
			"O,X,O,O,O,E,X\n" +
			"O,X,O,O,O,E,O\n" +
			"O,X,O,O,O,X,E\n" +
			"O,X,O,O,O,X,X\n" +
			"O,X,O,O,O,X,O\n" +
			"O,X,O,O,O,O,E\n" +
			"O,X,O,O,O,O,X\n" +
			"O,X,O,O,O,O,O\n" +
			"O,O,E,E,E,E,E\n" +
			"O,O,E,E,E,E,X\n" +
			"O,O,E,E,E,E,O\n" +
			"O,O,E,E,E,X,E\n" +
			"O,O,E,E,E,X,X\n" +
			"O,O,E,E,E,X,O\n" +
			"O,O,E,E,E,O,E\n" +
			"O,O,E,E,E,O,X\n" +
			"O,O,E,E,E,O,O\n" +
			"O,O,E,E,X,E,E\n" +
			"O,O,E,E,X,E,X\n" +
			"O,O,E,E,X,E,O\n" +
			"O,O,E,E,X,X,E\n" +
			"O,O,E,E,X,X,X\n" +
			"O,O,E,E,X,X,O\n" +
			"O,O,E,E,X,O,E\n" +
			"O,O,E,E,X,O,X\n" +
			"O,O,E,E,X,O,O\n" +
			"O,O,E,E,O,E,E\n" +
			"O,O,E,E,O,E,X\n" +
			"O,O,E,E,O,E,O\n" +
			"O,O,E,E,O,X,E\n" +
			"O,O,E,E,O,X,X\n" +
			"O,O,E,E,O,X,O\n" +
			"O,O,E,E,O,O,E\n" +
			"O,O,E,E,O,O,X\n" +
			"O,O,E,E,O,O,O\n" +
			"O,O,E,X,E,E,E\n" +
			"O,O,E,X,E,E,X\n" +
			"O,O,E,X,E,E,O\n" +
			"O,O,E,X,E,X,E\n" +
			"O,O,E,X,E,X,X\n" +
			"O,O,E,X,E,X,O\n" +
			"O,O,E,X,E,O,E\n" +
			"O,O,E,X,E,O,X\n" +
			"O,O,E,X,E,O,O\n" +
			"O,O,E,X,X,E,E\n" +
			"O,O,E,X,X,E,X\n" +
			"O,O,E,X,X,E,O\n" +
			"O,O,E,X,X,X,E\n" +
			"O,O,E,X,X,X,X\n" +
			"O,O,E,X,X,X,O\n" +
			"O,O,E,X,X,O,E\n" +
			"O,O,E,X,X,O,X\n" +
			"O,O,E,X,X,O,O\n" +
			"O,O,E,X,O,E,E\n" +
			"O,O,E,X,O,E,X\n" +
			"O,O,E,X,O,E,O\n" +
			"O,O,E,X,O,X,E\n" +
			"O,O,E,X,O,X,X\n" +
			"O,O,E,X,O,X,O\n" +
			"O,O,E,X,O,O,E\n" +
			"O,O,E,X,O,O,X\n" +
			"O,O,E,X,O,O,O\n" +
			"O,O,E,O,E,E,E\n" +
			"O,O,E,O,E,E,X\n" +
			"O,O,E,O,E,E,O\n" +
			"O,O,E,O,E,X,E\n" +
			"O,O,E,O,E,X,X\n" +
			"O,O,E,O,E,X,O\n" +
			"O,O,E,O,E,O,E\n" +
			"O,O,E,O,E,O,X\n" +
			"O,O,E,O,E,O,O\n" +
			"O,O,E,O,X,E,E\n" +
			"O,O,E,O,X,E,X\n" +
			"O,O,E,O,X,E,O\n" +
			"O,O,E,O,X,X,E\n" +
			"O,O,E,O,X,X,X\n" +
			"O,O,E,O,X,X,O\n" +
			"O,O,E,O,X,O,E\n" +
			"O,O,E,O,X,O,X\n" +
			"O,O,E,O,X,O,O\n" +
			"O,O,E,O,O,E,E\n" +
			"O,O,E,O,O,E,X\n" +
			"O,O,E,O,O,E,O\n" +
			"O,O,E,O,O,X,E\n" +
			"O,O,E,O,O,X,X\n" +
			"O,O,E,O,O,X,O\n" +
			"O,O,E,O,O,O,E\n" +
			"O,O,E,O,O,O,X\n" +
			"O,O,E,O,O,O,O\n" +
			"O,O,X,E,E,E,E\n" +
			"O,O,X,E,E,E,X\n" +
			"O,O,X,E,E,E,O\n" +
			"O,O,X,E,E,X,E\n" +
			"O,O,X,E,E,X,X\n" +
			"O,O,X,E,E,X,O\n" +
			"O,O,X,E,E,O,E\n" +
			"O,O,X,E,E,O,X\n" +
			"O,O,X,E,E,O,O\n" +
			"O,O,X,E,X,E,E\n" +
			"O,O,X,E,X,E,X\n" +
			"O,O,X,E,X,E,O\n" +
			"O,O,X,E,X,X,E\n" +
			"O,O,X,E,X,X,X\n" +
			"O,O,X,E,X,X,O\n" +
			"O,O,X,E,X,O,E\n" +
			"O,O,X,E,X,O,X\n" +
			"O,O,X,E,X,O,O\n" +
			"O,O,X,E,O,E,E\n" +
			"O,O,X,E,O,E,X\n" +
			"O,O,X,E,O,E,O\n" +
			"O,O,X,E,O,X,E\n" +
			"O,O,X,E,O,X,X\n" +
			"O,O,X,E,O,X,O\n" +
			"O,O,X,E,O,O,E\n" +
			"O,O,X,E,O,O,X\n" +
			"O,O,X,E,O,O,O\n" +
			"O,O,X,X,E,E,E\n" +
			"O,O,X,X,E,E,X\n" +
			"O,O,X,X,E,E,O\n" +
			"O,O,X,X,E,X,E\n" +
			"O,O,X,X,E,X,X\n" +
			"O,O,X,X,E,X,O\n" +
			"O,O,X,X,E,O,E\n" +
			"O,O,X,X,E,O,X\n" +
			"O,O,X,X,E,O,O\n" +
			"O,O,X,X,X,E,E\n" +
			"O,O,X,X,X,E,X\n" +
			"O,O,X,X,X,E,O\n" +
			"O,O,X,X,X,X,E\n" +
			"O,O,X,X,X,X,X\n" +
			"O,O,X,X,X,X,O\n" +
			"O,O,X,X,X,O,E\n" +
			"O,O,X,X,X,O,X\n" +
			"O,O,X,X,X,O,O\n" +
			"O,O,X,X,O,E,E\n" +
			"O,O,X,X,O,E,X\n" +
			"O,O,X,X,O,E,O\n" +
			"O,O,X,X,O,X,E\n" +
			"O,O,X,X,O,X,X\n" +
			"O,O,X,X,O,X,O\n" +
			"O,O,X,X,O,O,E\n" +
			"O,O,X,X,O,O,X\n" +
			"O,O,X,X,O,O,O\n" +
			"O,O,X,O,E,E,E\n" +
			"O,O,X,O,E,E,X\n" +
			"O,O,X,O,E,E,O\n" +
			"O,O,X,O,E,X,E\n" +
			"O,O,X,O,E,X,X\n" +
			"O,O,X,O,E,X,O\n" +
			"O,O,X,O,E,O,E\n" +
			"O,O,X,O,E,O,X\n" +
			"O,O,X,O,E,O,O\n" +
			"O,O,X,O,X,E,E\n" +
			"O,O,X,O,X,E,X\n" +
			"O,O,X,O,X,E,O\n" +
			"O,O,X,O,X,X,E\n" +
			"O,O,X,O,X,X,X\n" +
			"O,O,X,O,X,X,O\n" +
			"O,O,X,O,X,O,E\n" +
			"O,O,X,O,X,O,X\n" +
			"O,O,X,O,X,O,O\n" +
			"O,O,X,O,O,E,E\n" +
			"O,O,X,O,O,E,X\n" +
			"O,O,X,O,O,E,O\n" +
			"O,O,X,O,O,X,E\n" +
			"O,O,X,O,O,X,X\n" +
			"O,O,X,O,O,X,O\n" +
			"O,O,X,O,O,O,E\n" +
			"O,O,X,O,O,O,X\n" +
			"O,O,X,O,O,O,O\n" +
			"O,O,O,E,E,E,E\n" +
			"O,O,O,E,E,E,X\n" +
			"O,O,O,E,E,E,O\n" +
			"O,O,O,E,E,X,E\n" +
			"O,O,O,E,E,X,X\n" +
			"O,O,O,E,E,X,O\n" +
			"O,O,O,E,E,O,E\n" +
			"O,O,O,E,E,O,X\n" +
			"O,O,O,E,E,O,O\n" +
			"O,O,O,E,X,E,E\n" +
			"O,O,O,E,X,E,X\n" +
			"O,O,O,E,X,E,O\n" +
			"O,O,O,E,X,X,E\n" +
			"O,O,O,E,X,X,X\n" +
			"O,O,O,E,X,X,O\n" +
			"O,O,O,E,X,O,E\n" +
			"O,O,O,E,X,O,X\n" +
			"O,O,O,E,X,O,O\n" +
			"O,O,O,E,O,E,E\n" +
			"O,O,O,E,O,E,X\n" +
			"O,O,O,E,O,E,O\n" +
			"O,O,O,E,O,X,E\n" +
			"O,O,O,E,O,X,X\n" +
			"O,O,O,E,O,X,O\n" +
			"O,O,O,E,O,O,E\n" +
			"O,O,O,E,O,O,X\n" +
			"O,O,O,E,O,O,O\n" +
			"O,O,O,X,E,E,E\n" +
			"O,O,O,X,E,E,X\n" +
			"O,O,O,X,E,E,O\n" +
			"O,O,O,X,E,X,E\n" +
			"O,O,O,X,E,X,X\n" +
			"O,O,O,X,E,X,O\n" +
			"O,O,O,X,E,O,E\n" +
			"O,O,O,X,E,O,X\n" +
			"O,O,O,X,E,O,O\n" +
			"O,O,O,X,X,E,E\n" +
			"O,O,O,X,X,E,X\n" +
			"O,O,O,X,X,E,O\n" +
			"O,O,O,X,X,X,E\n" +
			"O,O,O,X,X,X,X\n" +
			"O,O,O,X,X,X,O\n" +
			"O,O,O,X,X,O,E\n" +
			"O,O,O,X,X,O,X\n" +
			"O,O,O,X,X,O,O\n" +
			"O,O,O,X,O,E,E\n" +
			"O,O,O,X,O,E,X\n" +
			"O,O,O,X,O,E,O\n" +
			"O,O,O,X,O,X,E\n" +
			"O,O,O,X,O,X,X\n" +
			"O,O,O,X,O,X,O\n" +
			"O,O,O,X,O,O,E\n" +
			"O,O,O,X,O,O,X\n" +
			"O,O,O,X,O,O,O\n" +
			"O,O,O,O,E,E,E\n" +
			"O,O,O,O,E,E,X\n" +
			"O,O,O,O,E,E,O\n" +
			"O,O,O,O,E,X,E\n" +
			"O,O,O,O,E,X,X\n" +
			"O,O,O,O,E,X,O\n" +
			"O,O,O,O,E,O,E\n" +
			"O,O,O,O,E,O,X\n" +
			"O,O,O,O,E,O,O\n" +
			"O,O,O,O,X,E,E\n" +
			"O,O,O,O,X,E,X\n" +
			"O,O,O,O,X,E,O\n" +
			"O,O,O,O,X,X,E\n" +
			"O,O,O,O,X,X,X\n" +
			"O,O,O,O,X,X,O\n" +
			"O,O,O,O,X,O,E\n" +
			"O,O,O,O,X,O,X\n" +
			"O,O,O,O,X,O,O\n" +
			"O,O,O,O,O,E,E\n" +
			"O,O,O,O,O,E,X\n" +
			"O,O,O,O,O,E,O\n" +
			"O,O,O,O,O,X,E\n" +
			"O,O,O,O,O,X,X\n" +
			"O,O,O,O,O,X,O\n" +
			"O,O,O,O,O,O,E\n" +
			"O,O,O,O,O,O,X\n" +
			"O,O,O,O,O,O,O\n"
		);

        String[] tables = new String[4];
        tables[0] = hash_4;
		tables[1] = hash_5;
		tables[2] = hash_6;
		tables[3] = hash_7;

        //Split each new line.
        String[] stringSplitter = tables[table - 4].split("\n");
        String[][] permutations = new String[stringSplitter.length][];
        int[] scores = new int[permutations.length];

        //Split string lines.
        for (int i = 0; i < stringSplitter.length; i++)
        {
            permutations[i] = stringSplitter[i].split(",");
        }

        //Loop over permutations.
        for (int i = 0; i < permutations.length; i++)
        {
            int score = 0;

            //Loop over permutation in sets of four.
            for (int o = 0; o < permutations[i].length - 3; o++)
            {
                int emptyCount = 0;
                int p1Count = 0;
                int p2Count = 0;

                //Count empty, player 1 and player 2 inserts.
                for (int p = 0; p < 4; p++)
                {
                    if (permutations[i][o + p].equals("E"))
                    {
                        emptyCount++;
                    }

                    else if (permutations[i][o + p].equals("X"))
                    {
                        p1Count++;
                    }

                    else
                    {
                        p2Count++;
                    }
                }

				// Center column.
                if(permutations[i].length == 7)
                {
                	if (permutations[i][3].equals("X"))
                	{
						score -= 25;
					}

                	if(permutations[i][3].equals("O"))
                	{
						score += 25;
					}
                }

				//Assign a score to the line.
				score += evaluateLine(emptyCount, p1Count, p2Count);
            }

            //Assign score to lookup table.
            scores[i] = score;
        }

        ////Print out table.
        //for (int i = 0; i < scores.length; i++)
        //{
        //    System.out.println(String.format("%7s" , scores[i] + ",") + "  //" + Arrays.deepToString(permutations[i]));
        //}

		//Return the lookup table.
        return scores;
    }

	/** Evaluates and returns a score for a line of four. */
    private static int evaluateLine(int emptyCount, int p1Count, int p2Count)
    {
		//Line evaluation score.
        int score = 0;

        if (p2Count == 4)
        {
            score += 100000;
        }

        else if (p2Count == 3 && emptyCount == 1)
        {
            score += 100;
        }

        else if (p2Count == 2 && emptyCount == 2)
        {
            score += 5;
        }

        else if (p1Count == 4)
        {
            score -= 100000;
        }

        else if (p1Count == 3 && emptyCount == 1)
        {
            score -= 100;
        }

        else if (p1Count == 2 && emptyCount == 2)
        {
            score -= 5;
        }

        return score;
    }
}